//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//
//   $ asciidoc -b html5 readme.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 readme.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf readme.adoc


= gvNIX web menu add-on
:Project:   gvNIX, un Addon de Spring Roo Suite
:Copyright: 2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y Administración Pública - CC BY-NC-SA 3.0
:Author:    Dirección General de Tecnologías de la Información, Asociación gvSIG, DISID Corporation, S.L.
:corpsite: www.gvnix.org
:doctype: article
:keywords: gvNIX, Documentation
:toc:
:toc-placement: left
:toc-title: Table of Contents
:toclevels: 4
:numbered:
:sectnumlevels: 4
:source-highlighter:  coderay
ifdef::backend-pdf[]
:pdf-style: asciidoctor
:pagenums:
endif::[]

_2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y
Administración Pública - Generalitat Valenciana._
This work is licensed under the http://creativecommons.org/licenses/by-sa/3.0/[Creative Commons Attribution-Share Alike
3.0 Unported License]. If you remix, transform, or build upon the material, you  must give appropriate credit and
distribute your contributions under the same license as the original.

[[introduction]]
Introduction
------------

Add-on to install and manage extended web menu.

[[project-contents]]
Project contents
----------------

This folder contains add-on sources and documents folder `docs` with
documentation of this project.

[[features]]
Features
--------

This add-ons have this features:

1.  Roo shell commands to manage web site map
* Move pages inside, before, after other pages or categories
* Hide/Show pages
* Change URL, label and message
2.  Role based page authorization management
3.  Quick and centralized access to page data: URL, label, message, etc

[[how-to-install]]
How to install
--------------

TODO
