//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//
//   $ asciidoc -b html5 td-addon-web-menu.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 td-addon-web-menu.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf td-addon-web-menu.adoc


= gvNIX - Spring Roo - Addon - Web MVC Menu
:Project:   gvNIX. Spring Roo based RAD tool
:Copyright: 2010 (C) Dirección General de Tecnologías de la Información - Conselleria d'Hisenda i Administració Pública
:Author:    DISID Corporation, S.L.
:corpsite: www.disid.com
:doctype: article
:keywords: gvNIX, Documentation
//:date: $Date: 2011-06-30 15:40:23 +0200 (jue, 30 jun 2011) $
:toc:
:toc-placement: left
:toc-title: Table of Contents
:toclevels: 4
:numbered:
:sectnumlevels: 4
:source-highlighter:  pygments
ifdef::backend-pdf[]
:pdf-style: asciidoctor
:pagenums:
:pygments-style:  bw
endif::[]


This work is licensed under the Creative Commons Attribution-Share Alike
3.0 Unported License. To view a copy of this license, visit
http://creativecommons.org/licenses/by-sa/3.0/ or send a letter to
Creative Commons, 171 Second Street, Suite 300, San Francisco,
California, 94105, USA.

[[introduction]]
Introduction
------------

This Roo add-on lets you to manage the application structure from Roo
shell.

[[requirements]]
Requirements
------------

This add-on must provide commands to manage the application structure
for Roo projects:

* Show menu tree
* Add/remove/update menu entries
* Show/hide menu entries
* Organize menu entries (categories, subcategories, …)
* support context menus

Additional features could be:

* Synchronize menu roles definition and Spring Security
annotations/definitions.
* DB storage for application structure
* Spring EL (expressions) support for menu entries visibility

[[analysis]]
Analysis
--------

[[application-structure-model]]
Application structure model
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Runtime classes to load the application structure that is stored in an
XML file, _menu.xml_.

Java files will be created in target project. Add-on contains the file
templates needed to generate them in `~.web.menu`

Runtime model is composed by:

* `MenuLoader.java` : Loads application structure into Menu instance and put it in application *ServletContext*.
* `Menu.java`       : Represents the application structure and information.
* `MenuItem.java`   : Represents an application page or an application pages group/category.

[[context-menu]]
Context menu
^^^^^^^^^^^^

`ContextMenuStrategy` interface defines an strategy that lets the
application to decide which items show in the menu depending on current
context.

Currently there are two default implementations:
`URLChildrenContextMenuStrategy` and `URLBrothersContextMenuStrategy`.

* `URLChildrenContextMenuStrategy`. This strategy decides which menu
item (root, subcategory, etc) should act as root by matching current
request URL with all menu entries target URLs. If a match item is found
the menu will render the children of the match menu entry.
* `URLBrothersContextMenuStrategy`. This strategy decides which menu
item (root, subcategory, etc) should act as root by matching current
request URL with all menu entries target URLs. If a match item is found
the menu will render the children of the match menu entry parent, that
is, it will render its brothers.

To create new strategies, implement `ContextMenuStrategy` and annotate
as Spring beans `@Component` and `@Configurable`.

[[web-artifacts]]
Web artifacts
~~~~~~~~~~~~~

* _gvnixmenu.tagx_ to render menu from `Application structure model`.
This tag renders the menu iterating all menu entries and taking in
account the context menu strategy.
* _gvnixitem.tagx_ renders a menu entry. Checks if Spring Security is
installed to decide what version of tag has to use: with or without
security checks.
* _/WEB-INF/view/menu.jspx_ will be modified to use _gvnixmenu.tagx_.
The contained structure info is moved to _menu.xml_.

[[roo-menuoperations-implementantion]]
Roo MenuOperations implementantion
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

After move the structure info to _menu.xml_, Roo components could manage
web pages via _MenuOperations_ component causing new info will added to
_menu.jspx_. To centralize page info, the add-on has their own
_MenuOperations_ implementation and disable the _MenuOperationsImpl_
that Roo provides by default.

[[features-roadmap]]
Features roadmap
~~~~~~~~~~~~~~~~

Features below should be implemented in future releases.

[[spring-security-integration]]
Spring Security integration
^^^^^^^^^^^^^^^^^^^^^^^^^^^

* Automatic sync with _applicationContext-security.xml_:
** If Spring Security is set, load default roles settings to _menu.xml_.
** If Spring Security is updated, update roles in _menu.xml_
* Detection of _Controller_ and _Controller Method_ Spring Security
configuration and set menu entries visibility based on that info.

[[menu-model-in-database]]
Menu model in database
^^^^^^^^^^^^^^^^^^^^^^

Load the application structure from a DB.

Currently you can do it manually by setting MenuLoader_
`MENU_CONFIG_FILE` constant to `null`. This disable all structure change
commands because there is no way to access model data.

[[visibility-check-based-on-spring-el-expressions]]
Visibility check based on Spring EL (expressions)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Another interesting feature could be add support to use Spring
Expression Language for items visibility.

[[proof-of-concept]]
Proof of Concept
----------------

* http://scmcit.gva.es/svn/gvnix-proof/trunk/petclinic-menu
* https://svn.disid.com/svn/disid/proof/gvnix/page-menu-app
* https://svn.disid.com/svn/disid/proof/gvnix/web-menu
* https://svn.disid.com/svn/disid/proof/spring_roo/struts-menu-integration
* https://svn.disid.com/svn/disid/proof/spring_roo/gvnix_web_menu

[[todo]]
TODO
----

* Check to disable menu Roo service http://projects.disid.com/issues/3919
** http://jira.springframework.org/browse/ROO-918
** http://jira.springframework.org/browse/ROO-904
** http://forum.springsource.org/showthread.php?t=89522
** http://jira.springframework.org/browse/ROO-950
