<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="ProductWebService" targetNamespace="http://ws.tiendavirtual.gvnix.org/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.tiendavirtual.gvnix.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<xs:schema elementFormDefault="unqualified" targetNamespace="http://ws.tiendavirtual.gvnix.org/" version="1.0" xmlns:tns="http://ws.tiendavirtual.gvnix.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="product" type="tns:product"/>
<xs:element name="productResponse" type="tns:productResponse"/>
<xs:complexType name="product">
    <xs:sequence/>
  </xs:complexType>
<xs:complexType name="productResponse">
    <xs:sequence>
      <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="return" type="xs:anyType"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="productResponse">
    <wsdl:part element="tns:productResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="product">
    <wsdl:part element="tns:product" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ProductWebServicePortType">
    <wsdl:operation name="product">
      <wsdl:input message="tns:product" name="product">
    </wsdl:input>
      <wsdl:output message="tns:productResponse" name="productResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ProductWebServiceSoapBinding" type="tns:ProductWebServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="product">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="product">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="productResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ProductWebService">
    <wsdl:port binding="tns:ProductWebServiceSoapBinding" name="ProductWebServicePortType">
      <soap:address location="http://localhost:8080/tiendavirtual/services/ProductWebService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
