= gvNIX Guidestyle
:backendurl:https://github.com/llaville/asciidoc-bootstrap-backend

A repository of gvNIX's styleguide for web application development made with
http://www.gvnix.org[gvNIX] tool.

The guide is written in AsciiDoc, generated by the AsciiDoc toolchain
and presented in HTML5 using Laurent Laville 's
{backendurl}[Bootstrap backend for AsciiDoc].

An AsciiDoc backend that renders the AsciiDoc source as HTML5
in the style of http://getbootstrap.com/[Bootstrap].

NOTE: Last branch 4 release was published on July 4, 2014 and support only
http://getbootstrap.com[Bootstrap 3]

== Setting up the build environment

* Install http://asciidoc.org[AsciiDoc] (8.6.6 or newer). Ensure that the
  command `asciidoc` is available on your `PATH`.

* Fetch and setup the _Bootstrap_ AsciiDoc backend by installing it into
  asciidoc backends through git (you will need AsciiDoc version 8.6.6 or newer)
+
----
$ asciidoc --backend install bootstrap-<version>.zip
----
+<version>+ is to be replaced by the latest version available of the backend.


== Build a html document

Follow these build instructions to generate a bootstrap webpage from the
AsciiDoc source files.

First, change into directory that contains the presentation AsciiDoc files.

Second, install gvNIX stylesheet for Bootstrap backend for 4.2.0 version.
Copy CSS file ./asciidoc-bootstrap.gvnix.css to $HOME/.asciidoc/backends/bootstrap/stylesheets

Next, generate a standalone HTML file that embeds all assets (stylesheets, JavaScript sources and images).

----
asciidoc -a data-uri gvnix-guia-estilo.adoc
----

You can now view the presentation slides.html in your browser.

== Documentation

You can read online or download eBooks format (chunked, chm, pdf, epub) at
http://laurent-laville.org/asciidoc/bootstrap/manual/current/en/

== Additional resources

Read {backendurl}[bootstrap.conf] to know how AsciiDoc dzslides backend works
to renders the AsciiDoc source as a dzslides presentation.

== Credits

Thanks to:

* https://github.com/mojavelinux[Dan Allen] who wrote the first version, available at https://github.com/mojavelinux/asciidoc-bootstrap-docs-backend

* {backendurl}[Laurent Laville] who improves and continues integration versions of Bootstrap backend for AsciiDoc.

==  Disclaimer

The software is provided "as is", without warranty of any kind, express or
implied, including but not limited to the warranties of merchantability,
fitness for a particular purpose and noninfringement. In no event shall the
authors or copyright holders be liable for any claim, damages or other
liability, whether in an action of contract, tort or otherwise, arising from,
out of or in connection with the software or the use or other dealings in the
software.

