gvNIX - Documentación de desarrollo
===================================

TODO
----

Temas a tener en cuenta para documentar
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Recopilado de alguna tarea de documentación.

* Remove all @Reference PathResolver declarations from classes and
retrieve PathResolver from ProjectMetadata instead #4615
* Descripción de la tarea https://jira.springsource.org/browse/ROO-2066
sobre la conveniencia de uso de las distintas clases habituales en un
add-on de Roo:
+
Currently ClasspathOperations is injected into DBRE and MVC services.
Roo Operations classes should only be called by other Operations
classes. This change will re-factor out all the methods from
ClasspathOperations into the existing TypeLocationService and a new
TypeManagementService. Also, entity-specific commands will be moved from
ClasspathCommands to a new EntityCommands class (and corresponding
EntityOperations interface and impl class) located in addon-entity.
Methods remaining in ClasspathCommands will be specific to classes and
interfaces only. ClasspathOperations and ClasspathOperations will be
removed after the MVC dependencies are changed to use
TypeLocationService and TypeManagementService. Below is the background
from Ben Alex about this change.
+
The general pattern is this:
** Utils are statless public abstract classes with public static
methods. They cannot be instantiated or injected with anything. It's OK
to pass things into the methods if it helps, but it is fairly unusual to
pass services or complex objects given utility methods are simple.
** Commands contain shell annotations. Generally call Operations, but
can call Services as well. Usually deal with formatting for user I/O.
Also ensure all types are of the intended format for successful method
invocation.
** Operations are stateless types which respond to UI commands and offer
their methods to other Operations types. The point was they were
different from Commands because they didn't deal with all the user I/O
(preparing method arguments etc) nor did they deal with complex
lifecycles requiring state and listener models like most of the metadata
infrastructure and services do. They just did something quite simple and
returned, with no ongoing lifecycle obligations. They are allowed call
services and other Operations objects. They aren't allowed call
Commands.
** Services can be called by anyone, including control flows unrelated
to a UI command, such as control flows instigated due to a
MetadataProvider or event. Services should never call an Operations or
Command object.
** Listeners are really a special type of Service. Most of the time a
so-called Service actually implements one of more Listeners.
** MetadataProviders and metadata infrastructure can call other metadata
infrastructure and Services. They're really just a very special type of
service (due to the ability to identify them and invoke and notify them
from string-based MIDs). They follow the same rules as Services, namely
they cannot call Operations or Commands.
+
As time has gone on, more complex add-ons have needed to do more complex
things and as such more and more logic has moved from Operations to
Services to make them more sophisticated and generally available. This
is what has happened in your case. It is starting to get to the point
where I question the value of keeping the Operations concept at all.
Sure, they're stateless and not listeners, but aside from that they seem
of negligible distinction versus a service. Maybe we should just rename
all Operations to Services for consistency? The critical thing is one
cannot "call up" to Commands, as it's silly to re-convert missing
arguments and figure out defaults etc like the Commands and Converter
infrastructure does.
* "addon create advanced" y "addon create wrapper"
* Joey infrastructure https://jira.springsource.org/browse/ROO-1372 -
http://projects.disid.com/issues/3814
* Allow third party addons to "override" methods generated by base
addons (ie express an ordering preference) -
https://jira.springsource.org/browse/ROO-795
* Ambigious command in Shell -
https://jira.springsource.org/browse/ROO-726
* Configuración de las convenciones Java, save actions, etc. para el
desarrollo del framework.

Esta parte de la documentación de introducción a la arquitectura interna
y información básica para el desarrollo de gvNIX.

Antes de empezar a trabajar en gvNIX es conveniente leer la siguiente
documentación:

* Operations, Commands, Utils et all:
https://jira.springsource.org/browse/ROO-2066
* Joey infraestructure: https://jira.springsource.org/browse/ROO-1372

Esta parte de la documentación contiene la información de desarrollo de
gvNIX

Introducción a OSGi, add-ons como componentes OSGi.

En esta parte podrá encontrar recursos útiles para el desarrollo de
gvNIX
