//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//   $ asciidoc -b html5 td-addon-web-mvc-datatables-filters_es.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 td-addon-web-mvc-datatables-filters_es.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf td-addon-web-mvc-datatables-filters_es.adoc
//
= {title}
:title:			gvNIX 1.3.1 - Filtros Simples
:author: 		DISID Corporation S.L. - Pivotal Software, Inc
:authorsite: 		www.disid.com
:copyright: 		CC BY-NC-SA 3.0
:doctype: 		article
:toc:
:toc-placement:		left
:toc-title:		Índice
:toclevels: 		4
:numbered:
:sectnumlevels:		4
ifdef::backend-pdf[]
:pdf-style:		asciidoctor
:pagenums:
//:pygments-style: 	bw
//:source-highlighter: 	pygments
endif::[]

[[descripcion-doc]]
== Descripción del documento

Documento de análisis y diseño técnico de una nueva funcionalidad de gvNIX que permita integrar un sistema de filtros simples en el componente Datatables.

[[diseño]]
== Diseño técnico

Esta nueva funcionalidad se implementará dentro del add-on *addon-web-mvc-datatables* de gvNIX. En los siguientes apartados se desarrolla el diseño técnico de este add-on en lo que se refiere al sistema de filtros simples en el componente Datatables.

[[analisis-solucion]]
=== Análisis de la solución

El sistema de filtros simples en el componente Datatables consiste en añadir una serie de “operaciones” a los filtros por columna aumentando así las posibilidades de filtrado. 

Para añadir esta nueva funcionalidad, será necesario aplicar los siguientes cambios en el proyecto gvNIX:

- Actualizar implementación de la *librería* encargada de generar las consultas del componente Datatables para detectar estas nuevas operaciones. Una vez detectadas, se podrá generar una condición válida que será añadida a la consulta que obtenga los datos a mostrar.

- Actualizar *fichero javascript* del componente Datatables para que los filtros por columna cambien de color al aplicar un filtrado. En caso de no ser una operación valida (alguna de las anteriores), el fondo cambiará a color rojo.

[[analisis-funcional]]
=== Análisis funcional

Implementar la solución indicada en el punto anterior requiere incluir un desarrollo a medida en el componente Datatables y en la librería Querydsl. 

Esta implementación a medida se incluirá en el proyecto generado al ejecutar el comando *web mvc datatables setup* del siguiente modo:

- Se incluirán las dependencias con la librería _querydsl_ actualizada para que acepte las operaciones de filtros simples.
- Se copiarán todos los recursos necesarios para el correcto funcionamiento del componente Datatables, entre ellos el fichero *jquery.dataTables.ext.gvnix.js* que incluirá la funcionalidad de destacar las operaciones en los filtros por columna.

[[diseño-tecnico]]
=== Diseño técnico

[[requisitos]]
==== Requisitos

1. Una vez instalado el componente Datatables y añadido sobre la capa web de una entidad, es necesario que el desarrollador ponga la propiedad *filterable* con valor a *true* en la columna que quiere incluir soporte para filtros simples. Si no se ha aplicado esta propiedad, la columna no dispondrá de _“Filtro por columna”_ y no añadirá las operaciones de filtrado anteriores.

[[operaciones-permitidas]]
==== Operaciones Permitidas

Las operaciones de filtrado permitidas en los filtros por columna serán:

- *Filtros para campos boolean:*
+
*NULO o ESNULO* +
El campo al que hace referencia es nulo
+
*NONULO* +
El campo al que hace referencia es no nulo

- *Filtros para fechas:*
+
Es importante saber que las fechas hay que introducirlas siempre con el formato indicado por el desarrollador:
+
*FECHA(dd/mm/aaaa)* +
Retorna una fecha exacta contenida con el formato indicado.
+
*ESANYO(aaaa)* +
Busca todos los registros de ese año
+
*ESMES(mm)* +
Busca todos los registros que tengan ese mes
+
*ESDIA(dd)* +
Busca todos los registros que tengan ese dia
+
*ENTREFECHA(fecha1;fecha2)* +
Busca todos los registros que se encuentren entre las fechas 1 y 2.

- *Filtros específicos para cadenas de caracteres*
+
*TERMINA(...)* +
Entre los paréntesis se pone la cadena a ser buscada teniendo en cuenta que esa cadena se encontrará en la parte derecha (terminan por).
+
*EMPIEZA(...)* +
Entre los paréntesis se pone la cadena a ser buscada teniendo en cuenta que esa cadena se encontrará en la parte izquierda (empiezan por).
+
*=cadena* +
Si se escribe = a una cadena, busca exactamente ese valor
+
*cadena* +
Es lo mismo que escribir =cadena

- *Filtros específicos para datos numéricos*
+
*numero* +
Si tan sólo se escribe un número, busca exactamente ese valor.
+
*=numero* +
Si tan sólo se escribe un número, busca exactamente ese valor.
+
*>numero* +
Si tan sólo se escribe un número, busca exactamente todos los valores mayores a ese número.
+
*<numero* +
Si tan sólo se escribe un número, busca exactamente todos los valores menores a ese número.
+
*>=numero* +
Si tan solo se escribe un número, busca exactamente todos los valores mayores e iguales a ese número
+
*<=numero* +
Si tan solo se escribe un número, busca exactamente todos los valores menores e iguales a ese número
+
*<>numero* +
Si tan sólo se escribe un número, busca exactamente todos los valores distintos a ese número.
+
*!=numero* +
Si tan sólo se escribe un número, busca exactamente todos los valores distintos a ese número
+
*ENTRENUMERO(n1;n2)* +
Busca todos los registros que se encuentran entre los dos números, siendo n1<n2.

