//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//
//   $ asciidoc -b html5 td-addon-web-mvc-datatables_es.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 td-addon-web-mvc-datatables_es.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf td-addon-web-mvc-datatables_es.adoc


= Análisis soporte tablas dinámicas
:Project:   gvNIX, un Addon de Spring Roo Suite
:Copyright: 2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y Administración Pública - CC BY-NC-SA 3.0
:Author:    Dirección General de Tecnologías de la Información, Asociación gvSIG, DISID Corporation, S.L.
:corpsite: www.gvnix.org
:doctype: article
:keywords: gvNIX, Documentation
:toc:
:toc-placement: left
:toc-title: Table of Contents
:toclevels: 4
:numbered:
:sectnumlevels: 4
:source-highlighter:  pygments
ifdef::backend-pdf[]
:pdf-style: asciidoctor
:pagenums:
:pygments-style:  bw
endif::[]

_2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y
Administración Pública - Generalitat Valenciana._ Esta obra está bajo la licencia
http://creativecommons.org/licenses/by-sa/3.0/es/[Reconocimiento-Compartir bajo la misma licencia 3.0 España]
de Creative Commons. Puede copiarla, distribuirla y comunicarla públicamente
siempre que especifique sus autores y comparta cualquier obra derivada bajo la
misma licencia.


[[descripcion-doc]]
== Descripción del documento

Documento de análisis y diseño técnico de una nueva funcionalidad de gvNIX que permita utilizar tablas dinámicas en los proyectos generados utilizando la herramienta de desarrollo gvNIX.

[[diseno]]
== Diseño técnico

Esta nueva funcionalidad se implementará en varios addons del proyecto:

- Se creará el add-on *addon-web-mvc-datatables* en el proyecto gvNIX que será el encargado de la generación de la capa web utilizando tablas dinámicas para la gestión de los datos.
- En el addon *addon-jpa* de gvNIX se crearán los comandos necesarios para poder generar los métodos que permitan utilizar operaciones en bloque (creación, actualización y eliminación de varios registros al mismo tiempo) en la capa de entidades.
- En el addon *addon-web-mvc* del proyecto gvNIX se crearán los comandos necesarios para poder publicar las operaciones en bloque de la capa de entidades en la capa web y que así puedan ser utilizadas por las tablas dinámicas.

En los siguientes apartados se desarrolla el diseño técnico de estos add-ons en lo que se refiere al soporte para tablas dinámicas en una aplicación generada utilizando la herramienta de desarrollo gvNIX.

[[analisis-solucion]]
=== Análisis de la solución
El soporte para tablas dinámicas consiste en que las aplicaciones desarrolladas utilizando la herramienta de desarrollo gvNIX, sean capaces de:

- Gestionar datos introducidos en la aplicación de forma dinámica.
- Cargar datos en modo asíncrono utilizando AJAX
- Ordenar datos por uno o más campos.
- Filtrado general y filtros por columna.
- Paginación de registros.
- Selección de registros.
- Operaciones en bloque (eliminar y actualizar varios componentes al mismo tiempo)
- Creación y actualización de registros sin abandonar la página de listado. (Edición _en linea_)
- Mostrar el registro recién creado en la primera fila de la tabla para que el usuario pueda localizarlo de forma rápida.
- Representar modelo relacional utilizando patrones de pantalla “Maestro – Detalle” permitiendo representar múltiples niveles de relación.
- Exportar listado en distintos formatos (PDF, CSV, TXT, etc..)
- Guardar configuración de la tabla.

Para implementar esta funcionalidad en un proyecto generado con la herramienta de desarrollo gvNIX los add-ons anteriores tendrán que llevar a cabo los siguientes cambios en el proyecto:

- Incluir ficheros *javascript*, *estilos*, *librerías*, *dependencias*, etc... necesarios para utilizar tablas dinámicas.
- Incluir *nuevos tagx* desarrollados que incluyan la estructura HTML y funcionalidades necesarias para representar las tablas dinámicas.
- Se deben cargar los componentes anteriores en un *fichero de carga*  para que estén disponibles en toda la aplicación.
- Generar *nuevas clases Java* que implementen métodos de acceso a datos con soporte para filtros y parámetros, métodos de generación de las listas, etc...

[[analisis-funcional]]
=== Análisis funcional

Implementar la solución indicada en el punto anterior requiere desarrollar los siguientes comandos gvNIX y los siguientes componentes:

*Comandos:*

- *jpa gvnix setup*: Se encargará de habilitar los comandos JPA implementados en gvNIX. Entre ellos los comandos relacionados con las operaciones en bloque.
- *jpa batch add*: Se encargará de generar operaciones en bloque para la entidad seleccionada. Parámetros:
* entity (Requerido): Entidad sobre la que se quieren generar operaciones en bloque
* type (Opcional): Nombre de la clase que se quiere generar. Si no se especifica se llamará del mismo modo que la entidad asociada.
- *jpa batch all*: Se encargará de generar operaciones en bloque para TODAS las entidades del proyecto.

- *web mvc batch setup*: Se encargará de instalar los componentes necesarios para poder publicar operaciones en bloque en la capa web.
- *web mvc batch add*: Se encargará de publicar las operaciones en bloque de una entidad en la capa web del proyecto. Parámetros:
* controller (Requerido): Controlador asociado a la entidad de la cual se quieren publicar las operaciones bloque.
* service (Opcional): Nombre del servicio que se generará y contendrá las operaciones en bloque. Por defecto, utilizará el mismo nombre que el controlador seleccionado.
- *web mvc batch all*: Se encargará de publicar las operaciones en bloque de TODAS las entidades en la capa web del proyecto.

- *web mvc datatables setup*: Se encargará de incluir todos los componentes , dependencias y librerías necesarias para que la aplicación generada utilice tablas dinámicas para la gestión de los datos.
- *web mvc datatables update tags*: Se encargará de actualizar los ficheros tags JSP del componente tablas dinámicas a la versión más actual.
- *web mvc datatables add*: Se encargará de añadir los métodos necesarios a una clase controladora asociada a una entidad para generar la capa web utilizando  tablas dinámicas para la gestión de los datos de dicha entidad.  Parámetros:
* type (Requerido): Clase controladora sobre la que se implementarán los métodos de generación de las tablas dinámicas.
* ajax (Opcional): Establecerá el modo de datos, por defecto tomará valor verdadero (AJAX), en caso de ser falso el modo de datos será DOM.
* mode (Opcional): Establecerá el modo de visualización de los datos de la tabla. En caso de tomar el valor 'show' se mostrarán los registros de manera individual utilizando la paginación para navegar entre ellos. En caso de tomar el valor 'list' se mostrará una lista paginada de los registros.
* inline (Opcional): Habilitará la edición y creación en linea, permitiendo crear y editar registros sin abandonar la vista.
- *web mvc datatables all*: Se encargará de añadir los métodos necesarios a TODAS las clases controladoras asociadas a las entidades del proyecto para generar la capa web utilizando tablas dinámicas para la gestión de los datos de dicha entidad.
- *web mvc datatables details add*: Se encargará de añadir una tabla dinámica detalle a una tabla dinámica maestro en base a una propiedad 1 a N de la entidad relacionada. Este comando permitirá representar modelos relacionales utilizando patrones de pantalla “Maestro-Detalle”. Se permite representar relaciones multinivel. Parámetros:
* type (Requerido): Clase controladora de la tabla dinámica maestra sobre la que se añadirá el nuevo detalle. Será necesario que se haya aplicado el comando web _mvc datatables add_ sobre dicho controlador.
* property (Requerido): Nombre de la propiedad 1:N del modelo relacional en la entidad asociada a la clase controladora seleccionada. Es necesario que se haya aplicado el comando web _mvc datatables add_ sobre el controlador de la entidad asociada que contiene la propiedad relacionada.

*Componentes:*

- *gvnix.dataTables.css*: Este fichero contendrá todas las clases y estilos necesarios para representar de forma correcta las tablas dinámicas en la aplicación generada.
- *jquery.dataTables.ext.gvnix.detail.js*: Este fichero contendrá las funciones javascript necesarias para generar las vistas de detalle de forma correcta.
- *jquery.dataTables.ext.gvnix.editing.js*: Este fichero contendrá las funciones javascript necesarias para que la edición en linea se genere de forma correcta.
- *jquery.dataTables.ext.gvnix.js*: Este fichero contendrá todas las funciones javascript necesarias para que las tablas dinámicas funcionen de forma correcta. Además, será el encargado de interactuar con el resto de ficheros javascript relacionados con el componente tablas dinámicas. Será el núcleo javascript del componente.
- *jquery.dataTables.ext.gvnix.rowclick.js*: Este fichero contendrá las funciones javascript necesarias para poder seleccionar filas haciendo doble click sobre ellas.
- *jquery.dataTables.ext.gvnix.rowontop.js*: Este fichero contendrá las funciones javascript necesarias para que los registros recién creados se muestren en la primera fila, permitiendo al usuario localiazrlos de forma rápida.
- *jquery.dataTables.ext.gvnix.selection.js*: Este fichero contiene las funciones javascript necesarias para permitir al usuario seleccionar los registros mostrados. Esta funcionalidad permitirá ejecutar las operaciones en bloque en caso de que hayan sido generadas, ya que se podrán seleccionar múltiples registros para su edición o eliminación.
- *action-column.tagx*: Este tag JSP se encargará de generar la estructura de componentes necesaria para visualizar una columna de acción en el listado. Estas columnas de acción invocarán las funciones javascript necesarias para interactuar con los registros. Por defecto, se añadirán funciones de edición, borrado y visualización de registros.
- *callback.tagx*: Este tag JSP se encargará de generar callbakcs de funciones javascript al ejecutarse distintos eventos del componente tablas dinámicas.
- *column.tagx*: Este tag JSP se encargará de generar la estructura de componentes necesaria para visualizar columnas en el componente tabla dinámica.
- *extraConf.tagx*: Este tag JSP se encargará de añadir propiedades extra de configuración del componente tablas dinámicas. Gracias a este componente el desarrollador podrá facilitar configuraciones personalizadas al componente tablas dinámicas.
- *list.tagx*: Este tag JSP se encargará de generar la estructura de componentes necesaria para visualizar de forma correcta el componente tabla dinámica.
- *redirect.tagx*: Este tag JSP se encargará de generar las funciones y estructura HTML necesarias para guardar los parámetros de la URL al abandonar la página de listado para efectuar alguna operación (creación, actualización, etc..) y así poder volver a ella al finalizar la operación.
- *set-input-values-from-request.tagx*: Este tag JSP se encargará de generar la estructura de componentes necesaria para enviar a los formularios de creación en linea los valores que establecen la relación y así poder crear detalles relacionados  sin seleccionar de forma manual el campo relacionado.

[[diseno-tecnico]]
=== Diseño técnico

Para integrar funcionalidades de tablas dinámicas en un proyecto generado utilizando la herramienta de desarrollo gvNIX, se utilizará el componente jQuery Datatables en su versión 1.9:

http://legacy.datatables.net/

Además, para integrar esta funcionalidad utilizando tecnología JSP, se utilizará la librería Dandelion Datatables en su versión 0.9.3

http://dandelion.github.io/datatables/

[[requisitos]]
==== Requisitos

1. Para que el componente Datatables esté disponible, es necesario se haya integrado el componente jQuery en el proyecto generado. Para ello es necesario haber ejecutado el comando *web mvc jquery setup*.
2. Para poder gestionar los datos de una entidad utilizando el componente Datatable, es necesario que aplique al controlador asociado el comando *web mvc jquery add*.

[[jpa-gvnix-setup]]
==== jpa gvnix setup

Para una mejor comprensión del comando, nos apoyaremos en el siguiente ejemplo para explicar qué acciones realizará en la aplicación:

`jpa gvnix setup`

Aplicará los siguientes cambios:

1. Se incluirán las siguientes dependencias en el fichero *pom.xml*
* Dependencia con la librería _QueryDSL_ con la versión 3.1.1
* Dependencia con el addon de JPA de gvNIX

[[jpa-batch-add]]
==== jpa batch add

Para una mejor comprensión del comando, nos apoyaremos en el siguiente ejemplo para explicar qué acciones realizará en la aplicación:

`jpa batch add --entity ~.domain.Owner`

Aplicará los siguientes cambios:

1. Generará la clase *OwnerBatchService.java*
2. Anotará la clase anterior con la anotación _@GvnixJpaBatch_
3. Se generarán los ITDs relacionados con la anotación, los cuales incluirán los métodos para ejecutar operaciones en bloque.

[[jpa-batch-all]]
==== jpa batch all

Efectuará los mismos cambios que el ejemplo anterior pero aplicándolos a todas las entidades del proyecto generado utilizando la herramienta de desarrollo gvNIX.

[[web-mvc-batch-setup]]
==== web mvc batch setup

Para una mejor comprensión del comando, nos apoyaremos en el siguiente ejemplo para explicar qué acciones realizará en la aplicación:

`web mvc batch setup`

Aplicará los siguientes cambios:

1. Actualizará el fichero *webmvc-config.xml* añadiendo un nuevo Bean que permitirá gestionar las peticiones recibidas utilizando AJAX y JSON.
2. Incluirá la dependencia en el fichero *pom.xml* con JSON Binding.

[[web-mvc-batch-add]]
==== web mvc batch add

Para una mejor comprensión del comando, nos apoyaremos en el siguiente ejemplo para explicar qué acciones realizará en la aplicación:

`web mvc batch add --controller ~.web.OwnerController`

Aplicará los siguientes cambios:

1. Anotará la clase controladora _OwnerController_ con la anotación _@GvNIXWebJpaBatch_
2. Generará los ITDs asociados a la anotación que incluirán los métodos de acceso desde la capa web a las operaciones en bloque de la capa de entidad.

[[web-mvc-batch-all]]
==== web mvc batch all

Efecturará los mismos cambios que el comando anterior pero aplicado a todas las clases controladoras del proyecto generado utilizando la herramienta de desarrollo gvNIX.

[[web-mvc-datatables-setup]]
==== web mvc datatables setup

Para una mejor comprensión del comando, nos apoyaremos en el siguiente ejemplo para explicar qué acciones realizará en la aplicación:

`web mvc datatables setup`

Aplicará los siguientes cambios:

1. Instalación de todos los *componentes* desarrollados para el correcto funcionamiento del componente Datatables. link:#analisis-funcional[(punto 2.2)]
2. Actualización del fichero *load-scripts.tagx* incluyendo los nuevos componentes en la carga de la página.
3. Creados *ficheros .properties i18n* donde se definen las cadenas en múltiples idiomas para el componente Datatables.
4. Se añadirán las siguientes dependencias al fichero *pom.xml*:
* Dependencia con el addon de Datatables
* Dependencia con la librería de Dandelion Datatables

[[web-mvc-datatables-update-tags]]
==== web mvc datatables update tags

Este comando solo estará disponible una vez ejecutado el comando de instalación de Datatables (web mvc datatables setup).
Comprobará si alguno de los tagx no coincide con el original y en caso de no coincidir lo devolverá a su versión original para evitar errores.

[[web-mvc-datatables-add]]
==== web mvc datatables add

Es necesario que se ejecute el comando *web mvc jquery add* sobre el controlador que generará el componente Datatable para un correcto funcionamiento.
Al aplicar el comando anterior sobre el controlador seleccionado, se anotará el controlador con _@GvNIXWebJQuery_ y se actualizarán todas las vistas JSP asociadas al controlador añadiendo el namespace de los componentes jQuery.
Para una mejor comprensión del comando, nos apoyaremos en el siguiente ejemplo para explicar qué acciones realizará en la aplicación:

`web mvc datatables add --type ~.web.OwnerController`

Aplicará los siguientes cambios:

1. Anotará la clase controladora _OwnerController_ con con la anotación _@GvNIXDatatables_
2. Se generarán los ITDs relacionados con la anotación anterior, los cuales implementarán los métodos necesarios para acceder a los datos del listado utilizando filtros,  generar el componente Datatable de forma correcta, etc..
3. Se actualizarán las vistas JSP con la estructura necesaria para generar componentes Datatables.

[[web-mvc-datatables-all]]
==== web mvc datatables all

Efectuará los mismos cambios que el comando anterior pero para TODOS los controladores asociados a una entidad que tengan aplicada la anotación _@GvNIXWebJQuery._

[[web-mvc-datatables-details-add]]
==== web mvc datatables details add

Para una mejor comprensión del comando, nos apoyaremos en el siguiente ejemplo para explicar qué acciones realizará en la aplicación:

`web mvc datatables detail add --type ~.web.OwnerController --property pets`

Aplicará los siguientes cambios:

1. Actualizará la anotación _@GvNIXDatatables_ del controlador _OwnerController_ añadiendo la propiedad _detailFields_ con el valor _pets_.
2. Esta propiedad, actualizará el método de generación de la vista de Datatables añadiendo este nuevo campo como detalle en el ITD asociado al controlador.
3. Recordar que para que el detalle funcione de forma correcta es necesario que se aplique el comando *web mvc datatables add* sobre el controlador asociado a la entidad _Pet_.


[[addon-gvnix-datatables---rowontop]]
== Addon gvNIX Datatables - rowOnTop

* Componentes involucrados en el proceso:
** datatables/list.tagx
** datatables/table.tagx
** datatables/jQuery.dataTables.ext.gvnix.js
** datatables/jQuery.dataTables.ext.gvnix.rowontop.js
** datatables/jQuery.dataTables.ext.gvnix.editing.js
** *_Roo_GvNIXDatatables.aj
** DatatableUtils.java

[[descripción-de-la-funcionalidad]]
=== Descripción de la funcionalidad

* La funcionalidad rowOnTop permite visualizar el registro que acaba de
ser creado/editado en la primera posición de la lista, así como
seleccionarlo y mostrar sus detalles en caso de que los tuviese.

=== Flujo de trabajo: Creación de maestro en formulario independiente

* Durante el pintado de un componente Datatable con creación en formulario
independiente, el fichero table.tagx se encarga de añadir el botón de `+`
en la parte superior izquierda. Este botón `+`, redirige a un formulario
de creación independiente. En la URL a la que enlaza el botón `+`
se encuentra el parámetro  `dtt_table_id_hash`, el cual indica a qué
Datatable corresponde esa llamada (para poder diferenciarlo en el retorno).
Este parámetro es generado en base al *id* de la tabla.

* Creación del registro en el formulario independiente.

* Al guardar el registro, se accede al método `createDatatableDetail` del
documento _Roo_GvNIXDatatables.aj y se añade un flash attribute con
key `dtt_row_on_top_ids` y valor el id del nuevo registro creado,
además del valor de `dtt_table_id_hash` recibido.

* Una vez guardado el registro, volvemos a mostrar el datatable. Para generar
el Datatable, el fichero table.tagx comprueba si existe el parámetro
`dtt_row_on_top_ids` en la petición. En caso de que exista generará el
datatable con la configuración para el plugin-datatable 'rowsOnTop', que
incluirá el id del registro recién creado identificado como 'asRowOnTopIds'
y el identificador del Datatable al que pertenece la petición de creación
identificado como 'asParentTableIdHash'.

* Durante la generación del Datatable, se inicializa el plugin-datatable
`rowontop` desde el fichero `jQuery.dataTables.ext.gvnix.rowontop.js`.
Al acceder a la función `fnConstruct`, en caso de que se detecte el anterior
objeto añadido `rowsOnTop` se guardan los valores de `asRowOnTopIds` y
`asParentTableIdHash` como parte de la configuración del datatable, para que
estén siempre accesibles en el elemento generado.

* Una vez inicializado el widget datatable, realizará la petición de los datos
al *controller*, entrando por el método `findAllXXX` del fichero
`_Roo_GvNIXDatatables.aj` y utilizando el request de la petición se
llama al método `getPropertyMap` y se añade a la variable `baseSearchValuesMap`
el identificador del nuevo registro creado con el key `dtt_row_on_top_ids`.

* Utilizando la anterior variable `baseSearchValuesMap` se utiliza el método
`findByCriteria` incluído en `DatatableUtils.java`. Éste método se encargará
de obtener el valor del parámetro `dtt_row_on_top_ids` en caso de que esté
presente en la petición. Una vez obtenido el id del último registro creado,
se modifica la consulta para mostrar en primera posición el registro con
el mismo id. Se devuelve el listado con el registro creado en la primera
posición y se añade al objeto Datatable.

* Al pintar los datos en el widget datatable, se invoca el callback registrado
en la función `_fnRegisterDrawCallback` del fichero `jQuery.dataTables.ext.gvnix.rowontop.js`.
En este momento, si el Datatable que se está pintando es
el que invocó el formulario de creación, se marca el registro.
En caso de que el datatable disponga de `rowclick` se seleccionará utilizando
la función `fnSetLastClicked` y se mostrarán sus detalles, sin embargo, si no
dispone de `rowclick` se marcará con una clase rowOnTop pero no se seleccionará.


=== Flujo de trabajo: Creación de maestro en formulario en linea

* Durante el pintado de un componente Datatable con creación en formulario en
linea, se utilizan las funciones declaradas en
`jQuery.dataTables.ext.gvnix.editing.js` para generar el formulario de creación
que aparece en la parte superior, y que nos permite generar nuevos registros
sin abandonar la página. En concreto se utiliza la función `fnBeginCreate`.

* La función `fnBeginCreate` solicita la página `create.jspx` y prepara el
formulario de creación en base a los campos de la página recibida, añadiendo
un botón de `Envío` para guardar los datos.

* Después de rellenar los datos, se presiona el botón de envio, y se llama a la
función `fnSendCreationForm` de  `jQuery.dataTables.ext.gvnix.editing.js`.
Se guardan los datos y mediante la función `fnSetRowsOnTop` inicializa el
dataTable para que muestre el registro creado en primera posición y repinta
la tabla, invocando a los mismos callbacks que en el caso del maestro.

* A diferencia de la creación en un formulario independiente, no necesita
facilitar el identificador de la tabla, ya que siempre es el mismo datatable
sobre el que se va a realizar el rowOnTop el que se repinta.

=== Flujo de trabajo: Creación de detalle en formulario independiente

*Al igual que en la creación del maestro, durante el pintado de un componente
Datatable con creación en formulario independiente, el fichero table.tagx
se encarga de añadir el botón de `+` en la parte superior izquierda.
Este botón `+`, redirige a un formulario de creación independiente.
En la URL a la que enlaza el botón `+` se encuentra el parámetro
`dtt_table_id_hash`, el cual indica a qué Datatable corresponde esa llamada.

* Creación del registro en el formulario independiente.

* Al guardar el registro, se accede al método `createDatatableDetail`
del documento _Roo_GvNIXDatatables.aj y se añade un flash attribute con
key `dtt_row_on_top_ids` y valor el id del nuevo registro creado.

* Una vez guardado el registro, en primer lugar se volverá a mostrar
el datatable maestro. Para generar el Datatable, el fichero table.tagx
comprueba si existe el parámetro `dtt_row_on_top_ids` en la petición.
En caso de que exista generará el datatable con el objeto 'rowsOnTop',
que incluirá el id del registro recién creado identificado como 'asRowOnTopIds'
 y el identificador del Datatable al que pertenece la petición de creación
 identificado como 'asParentTableIdHash'.

* El maestro cargará mediante el `loadDetail` del fichero `list.tagx`
los detalles relacionados. A estos detalles, se les enviará mediante el
parámetro `dtt_row_on_top_ids` el id del registro que acaba de ser creado
 y se generará el detalle de la misma forma que el maestro.

* Ahora que se ha generado el datatable conservando el id del registro
que ha sido creado y el identificador de la tabla que llamó al formulario
de creación, obtenemos el listado de datos a mostrar. Para ello, se accede
al método `findAllXXX` del fichero `_Roo_GvNIXDatatables.aj` y utilizando
el request de la petición se llama al método `getPropertyMap` y se añade a
la variable `baseSearchValuesMap` el identificador del nuevo registro creado
con el key `dtt_row_on_top_ids`.

* Utilizando la anterior variable `baseSearchValuesMap` se utiliza el método
`findByCriteria` incluído en `DatatableUtils.java`. Éste método se encargará
 de obtener el valor del parámetro `dtt_row_on_top_ids` en caso de que esté
 presente en la petición. Una vez obtenido el id del último registro creado,
  se modifica la consulta para mostrar en primera posición el registro con
  el mismo id. Se devuelve el listado con el registro creado en la primera
  posición y se añade al objeto Datatable.

* Al pintar los datos en el objeto datatable, se invoca el callback registrado
en la función `_fnRegisterDrawCallback` del fichero
`jQuery.dataTables.ext.gvnix.rowontop.js`. En un primer momento se invocarán
los callbacks del maestro. Utilizando el identificador del formulario que lanzó
 la creación, detectaremos que este no es el datatable al que pertenece el
 nuevo registro y no realizaremos ninguna acción. Si el detalle que se está
 pintando es el que invocó el formulario de creación, se marca el registro.
 En caso de que el datatable disponga de `rowclick` se seleccionará utilizando
 la función `fnSetLastClicked` y se mostrarán sus detalles, sin embargo, si
 no dispone de `rowclick` se marcará con una clase rowOnTop pero no se
 seleccionará.

=== Flujo de trabajo: Creación de detalle en formulario en linea

* La creación de detalles con formulario en linea funcionan del mismo modo que
los maestros con formulario en linea. Esto se debe a que cuando existe la
creación en linea, los nuevos registros añadidos siempre pertenecen al
Datatable que se repinta y no es necesario guardar un identificador de tabla.

=== Flujo de trabajo: Actualización de maestro/detalle en formulario independiente

* La actualización de maestros en formularios independientes funciona del mismo
modo que la creación. La principal diferencia es que al generar el
widget datatable se añade el parámetro `dtt_table_id_hash` al botón de edición,
tanto en la edición por fila como en la edición general, al igual que se
añadía en el botón `+`. Gracias a esto, identificaremos en todo momento
qué datatable invocó el formulario de actualización.

=== Fujo de trabajo: Actualización de maestro/detalle en formulario en linea

* Cuando se edita un registro en linea no se mueve a la primera posición.


=== ACTUALES PROBLEMAS: Detalle rowOnTop incorrecto

* El principal problema que aparece es el siguiente:

** Cuando se carga un listado, se búsca el atributo `dtt_row_on_top_ids`.
Si existe se muestra en la primera posición el registro con el id guardado
en el atributo `dtt_row_on_top_ids`. Al crear un maestro se muestra en primera
posición de forma correcta. Si a ese maestro le asignamos un detalle,
el detalle se muestra en primera posición de manera correcta. Si cambiamos la
selección del maestro nos aparecerán los detalles asociados a la nueva selección
 si los tuviese. Al entrar en el formulario de creación del detalle y volver al
 listado del Datatable (sin haber creado ningún nuevo registro)
 aparece en el detalle, el registro asociado al maestro anterior.

** Este error es debido a que al volver a cargar el `list.tagx`,
todavía dispone del parámetro `dtt_row_on_top_ids` y se pone en primera
posición el registro con id creado en el anterior maestro.

