//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//
//   $ asciidoc -b html5 td-addon-web-mvc-loupefield-extra-columns_es.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 td-addon-web-mvc-loupefield-extra-columns_es.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf td-addon-web-mvc-loupefield-extra-columns_es.adoc


= N:1 Columnas adicionales
:Project:   gvNIX, un Addon de Spring Roo Suite
:Copyright: 2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y Administración Pública - CC BY-NC-SA 3.0
:Author:    Dirección General de Tecnologías de la Información, Asociación gvSIG, DISID Corporation, S.L.
:corpsite: www.gvnix.org
:doctype: article
:keywords: gvNIX, Documentation
:toc:
:toc-placement: left
:toc-title: Table of Contents
:toclevels: 4
:numbered:
:sectnumlevels: 4
:source-highlighter:  pygments
ifdef::backend-pdf[]
:pdf-style: asciidoctor
:pagenums:
:pygments-style:  bw
endif::[]


_2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y
Administración Pública - Generalitat Valenciana._ Esta obra está bajo la licencia
http://creativecommons.org/licenses/by-sa/3.0/es/[Reconocimiento-Compartir bajo la misma licencia 3.0 España]
de Creative Commons. Puede copiarla, distribuirla y comunicarla públicamente
siempre que especifique sus autores y comparta cualquier obra derivada bajo la
misma licencia.

[[descripcion-doc]]
== Descripción del documento

Documento de análisis y diseño técnico de una nueva funcionalidad de gvNIX que permita al desarrollador, utilizando el componente lupa en atributos de relaciones N:1, obtener varias columnas del elemento relacionado y así poder autocompletar otros componente del formulario con los valores de las mismas.

[[diseno]]
== Diseño técnico

Esta nueva funcionalidad se implementará dentro del add-on *addon-web-mvc-loupefield* de gvNIX. En los siguientes apartados se desarrolla el diseño técnico de este add-on en lo que se refiere al sistema de obtención de columnas adicionales del componente lupa.

[[analisis-solucion]]
=== Análisis de la solución

El sistema de columnas adicionales del componente lupa consiste en que el desarrollador pueda establecer una serie de columnas adicionales que se obtendrán junto con el valor establecido para el campo lupa. El desarrollador podrá utilizar estas columnas adicionales para rellenar otros componentes del formulario con el valor de las mismas.

Por ejemplo, al buscar una Ciudad en el componente lupa se muestra el _nombre_ de la _ciudad_ en el desplegable con los resultados. Al seleccionar una de las ciudades el campo _código postal_ del formulario debe autocompletarse de forma automática con el valor de la columna codigo postal asociada a la Ciudad obtenida en el componente lupa.

Para añadir esta nueva funcionalidad, será necesario aplicar los siguientes cambios en el proyecto gvNIX:

- Actualizar *tagx* del componente lupa para que permita al desarrollador especificar qué columnas adicionales quiere obtener y qué función javascript se ejecutará al seleccionar un registro.
- Actualizar *fichero javascript* del componente lupa para que devuelva las columnas adicionales especificadas por el desarrollador y que además, sea capaz de invocar a la función javascript especificada por el desarrollador al seleccionar un registro.

La implementación necesaria para autocompletar otros componentes del formulario debe realizarla el propio desarrollador en la función javascript que se invocará al seleccionar un registro.

[[analisis-funcional]]
=== Análisis funcional

Implementar la solución indicada en el punto anterior requiere incluir un desarrollo a medida en el componente lupa.

Esta implementación a medida se incluirá en el proyecto generado al ejecutar los siguientes comandos:

- *web mvc loupe setup*

* Se copiarán todos los recursos necesarios para el correcto funcionamiento del componente lupa, entre ellos el fichero *jquery.loupeField.ext.gvnix* y el fichero *loupe.tagx* que incluirán las funcionalidades para obtener las columnas adicionales e invocar la función javascript al seleccionar un registro.

- *web mvc loupe field*

* Especificando el parámetro opcional *--additionalFields* se añadirá la propiedad additionalFields al tag del componente lupa que se incluirá en la vista JSP obteniendo así columnas adicionales.

[[diseno-tecnico]]
=== Diseño técnico

[[requisitos]]
==== Requisitos

1. Para poder utilizar el componente lupa y que sus comandos estén disponibles, es necesario haber instalado el componente jQuery  en el proyecto generado. Para ello se debe ejecutar el comando *web mvc jquery setup*.

[[loupe-tagx]]
==== Loupe.tagx

Se añadirá la propiedad *_additionalFields_* al tag del componente lupa, permitiendo al desarrollador especificar las columnas adicionales que quiere obtener.

Además, también se añadirá la propiedad *onSet* al tag del componente lupa, permitiendo al desarrollador especificar qué función javascript será invocada al seleccionar un registro.

Un ejemplo de cómo quedaría especificado este tag en la vista JSP de creación sería el siguiente:

[source,jsp]
----
<loupefield:loupe pass:quotes[*additionalFields="codigoPostal,provincia"*] controllerPath="ciudades" field="ciudad" id="c_com_springsource_petclinic_domain_Ciudad_ciudad" itemValue="id" items="${ciudadeses}" listPath="ciudades/list" pass:quotes[*onSet="onSetCiudad"*] path="/ciudades" pkField="id" z="user-managed"/>
----

El componente lupa anterior, buscar las ciudades y devuelve la información del _id_, _codigoPostal_ y la provincia asociada a la ciudad seleccionada. Al seleccionar un registro, se invocará a la función _onSetCiudad_.

[[fichero-javascript]]
==== Fichero Javascript: jquery.loupeField.ext.gvnix.js


Se actualizará la función encargada de obtener los registros para que devuelva todas aquellas propiedades que estén incluidas en el atributo *additionalFields* especificado en el tagx.

Se añadirá un evento *onClick* en la lista desplegable de los registros encontrados. Esta función onClick invocará a la función definida en el atributo *onSet* especificado en el tagx.

[[actualizacion-elementos]]
==== Actualización de elementos del formulario

Un ejemplo de la implementación de la función *onSet* que debe realizar el desarrollador para cambiar el valor de otro elemento del formulario sería el siguiente:

[source,js]
----
function onSetCiudad(id, instancia, data){
	var codigoPostal = jQuery('#codigo_postal_input');
	codigoPostal.val(data.ciudad.codigoPostal)
}
----

La función anterior se invocará al seleccionar una ciudad en el componente lupa.

Esta función recibirá el id con el valor del campo relacionado, la instancia de la lupa e información adicional del registro seleccionado en el parámetro *data*.

Al ejecutarse, actualiza el campo Código Postal del formulario con el valor *codigoPostal* asociado a la ciudad seleccionada en el componente lupa.
