//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//
//   $ asciidoc -b html5 ug-occ-addon.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 ug-occ-addon.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf ug-occ-addon.adoc


= gvNIX OCC Add-on User Guide
:Project:   gvNIX. Spring Roo based RAD tool
:Copyright: 2010 (C) Dirección General de Tecnologías de la Información - Conselleria d'Hisenda i Administració Pública
:Author:    DISID Corporation, S.L.
:corpsite: www.disid.com
:doctype: book
:keywords: gvNIX, Documentation
:toc:
:toc-placement: left
:toc-title: Table of Contents
:toclevels: 4
:numbered:
:sectnumlevels: 4
:source-highlighter:  pygments
ifdef::backend-pdf[]
:pdf-style: asciidoctor
:pagenums:
:pygments-style:  bw
endif::[]


[[introduction]]
Introduction
------------

Add-on to create the JPA extension that enables versioning by comparing
the old and new entity state without the need to alter legacy databases.

[[requirements]]
Requirements
~~~~~~~~~~~~

* JDK 1.6+
* Maven 2+
* gvNIX - Spring Roo - Addon - Optimistic Concurreny Control
* Eclipse Helios 3.6.0 (optional)

[[install-addon-services-management]]
Install Addon Services Management
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Options:

* To install gvNIX 0.6.0 that contains the add-on installed.

* OR, to install in Spring Roo 1.1.2::
** Trust on PGP KEY ID used to sign the add-on. Note that gvNIX project
  members have their PGP KEYs IDs published at
  https://code.google.com/p/gvnix/people/list:
+
----------------------------
pgp trust --keyId 0xC5FC814B
----------------------------

** Run the command below:
+
-----------------------------------------------------------------
addon install bundle --bundleSymbolicName org.gvnix.occ.roo.addon
-----------------------------------------------------------------

[[use-case-occ-support-in-pet-clinic]]
Use case: OCC support in Pet clinic
-----------------------------------

Create a new directory for the project:

[source, sh]
--------------
Bash shell:

  mkdir clinic
  cd clinic
--------------

Start gvNIX:

[source,java]
------------------------------------------------------------------------------
clinic$ gvnix.sh
    ____  ____  ____
   / __ \/ __ \/ __ \
  / /_/ / / / / / / /
 / _, _/ /_/ / /_/ /   1.1.2.RELEASE [rev fbc33bb]
/_/ |_|\____/\____/   gvNIX distribution 0.6.0


Welcome to Spring Roo. For assistance press TAB or type "hint" then hit ENTER.
roo>
------------------------------------------------------------------------------

Create the project:

[source, sh]
----------------------
roo> script clinic.roo
----------------------

Set concurrency control on _Pet_ entity:

[source, sh]
----------------------------------------------------------------------------------------------------------------------------------
roo> occ checksum set --entity ~.domain.Pet

Updated ROOT/pom.xml [Added dependency org.gvnix:org.gvnix.occ.roo.addon:0.6.0]
Updated SRC_MAIN_JAVA/com/springsource/petclinic/domain/Pet.java
Created SRC_MAIN_JAVA/com/springsource/petclinic/domain/Pet_Roo_gvNIX_occChecksum.aj
Updated SRC_MAIN_WEBAPP/WEB-INF/views/pets/list.jspx
Updated SRC_MAIN_WEBAPP/WEB-INF/views/pets/show.jspx
Updated SRC_MAIN_WEBAPP/WEB-INF/views/pets/create.jspx
Updated SRC_MAIN_WEBAPP/WEB-INF/views/pets/update.jspx
Updated SRC_MAIN_WEBAPP/WEB-INF/i18n/application.properties
Updated SRC_MAIN_WEBAPP/WEB-INF/views/pets/list.jspx
Updated SRC_MAIN_WEBAPP/WEB-INF/views/pets/show.jspx
Updated SRC_MAIN_WEBAPP/WEB-INF/views/pets/create.jspx
Updated SRC_MAIN_WEBAPP/WEB-INF/views/pets/update.jspx
Updated SRC_MAIN_JAVA/com/springsource/petclinic/domain/Pet_Roo_Jpa_ActiveRecord.aj
Updated SRC_MAIN_JAVA/com/springsource/petclinic/domain/Pet_Roo_ToString.aj
Updated SRC_TEST_JAVA/com/springsource/petclinic/domain/PetIntegrationTest_Roo_IntegrationTest.aj
[Spring Roo Process Manager Background Polling Thread] Updated SRC_MAIN_JAVA/com/springsource/petclinic/domain/Pet_Roo_ToString.aj
----------------------------------------------------------------------------------------------------------------------------------

[[add-on-commands]]
Add-on commands
~~~~~~~~~~~~~~~

Two new commands will be available:

1.  `occ checksum set`: Apply this occ implementation to a existing
`@RooJpaActiveRecord`. Add the gvNIX Optimistic Concurrecy Control
Checksum based behaivor to a Entity.
+
Options:

* _entity_: The name of the entity object to add OCC
* _fieldName_ (optional): The name of the field to use to store de
checksum value
* _digestMethod_ (optional): The name of the type of digest method to
compute the checksum

2.  `occi checksum all`: Apply this occ implementation to all existing
`@RooJpaActiveRecord`. Add the gvNIX Optimistic Concurrency Control
Checksum based behaivor to all entities in project. If any of them has
already been configure no changes will be applied to this entity.
+
Options:

* _fieldName_ (optional): The name of the field to use to store de
checksum value
* _digestMethod_ (optional): The name of the type of digest method to
compute the checksum

See shell command help for more information
