//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//
//   $ asciidoc -b html5 readme.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 readme.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf readme.adoc


= gvNIX Service Layer Add-on
:Project:   gvNIX, un Addon de Spring Roo Suite
:Copyright: 2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y Administración Pública - CC BY-NC-SA 3.0
:Author:    Dirección General de Tecnologías de la Información, Asociación gvSIG, DISID Corporation, S.L.
:corpsite: www.gvnix.org
:doctype: article
:keywords: gvNIX, Documentation
:toc:
:toc-placement: left
:toc-title: Table of Contents
:toclevels: 4
:numbered:
:sectnumlevels: 4
:source-highlighter:  pygments
ifdef::backend-pdf[]
:pdf-style: asciidoctor
:pagenums:
:pygments-style:  bw
endif::[]


_2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y
Administración Pública - Generalitat Valenciana._
This work is licensed under the http://creativecommons.org/licenses/by-sa/3.0/[Creative Commons Attribution-Share Alike
3.0 Unported License]. If you remix, transform, or build upon the material, you  must give appropriate credit and
distribute your contributions under the same license as the original.

[[introduction]]
Introduction
------------

This project generates the addon to generate and manage service classes
and export and import to web services.

[[features]]
Features
--------

TBC

This are features contained:

[[development]]
Development
-----------

Create two Operation classes, one for service layer management
`ServiceLayerOperationsImpl` and another for manage the web service
layer `WebServiceLayerOperationsImpl`.

[[commands]]
Commands
~~~~~~~~

* remote service class –class:
* remote service operation –class clase –name nombreOperacion –return
clase:
* remote service define ws –class clase –name nombreServicio:
* remote service export operation –class clase –method
nombreMetodoEntidad –name nombreAPublicar:
* remote service import ws –endPoint urlOPropiedad –wsdl url2wsdl.xml:
* remote service entity –class nombreClase:
* remote service ws list : List all project services (exported/imported)
in console.
* remote service security ws –class importedServiceClass –certificate
path_to_certificate_file –password password –alias alias

Adds message signature to a imported Axis web service. Certificate file
will be copy into project resource.

[[how-to-install]]
How to install
--------------

Important:

You must update *JavaParserMethodMetadata* class in
`gvnix/trunk/code/roo/classpath-javaparser` ROO Add-on with patch
*issue_3879_JavaParserMethodMetadata.patch* in:
http://projects.disid.com/issues/3879

And then, run `mvn clean install` in roo sources directory to use this
update.

[[about-import-ws-based-on-wsdl]]
About import WS based on WSDL
-----------------------------

If the WSDL is under a secure server and the access is through HTTPS and
the host uses a certificate non reliable by the JVM the add-on will
handle the unreachable source error importing, automatically, the
certificates in certificate chain to JVM cacerts keystore. That is,
`$JAVA_HOME/jre/lib/security/cacerts` in SUN JDK distribution. Also it
creates a local copy of the needed certificates under
`src/main/resources` folder of the project, with `.cer` extension, so
you can distribute them for its installation in other environments.

Notice that this will be possible only if `cacerts` file is writable by
the system user running the add-on and the password of the keystore is
`changeit` (the default keystore password). If these two conditions are
not met, the add-on only will create the local copy of the certs in
certificate chain and you are the responsible of its instalation in your
cacerts keystore (see keytool manual for keystore manipulation).
