Comandos del add-on OCC
-----------------------

//Push down level title
:leveloffset: 2


Para una descripción detallada de las características del add-on
consultar la documentación del link:#addon-persistence[add-on OCC
(Optimistic Concurrency Control)].

.Comandos del add-on OCC
[width="100%",cols="33%,67%",options="header",]
|=======================================================================
|Comando |Descripción
|link:#apendice-comandos_addon-persistence_occchecksum_occ-checksum-set[occ
checksum set] |Establece un control de concurrencia optimista mediante
una suma de comprobación (checksum) para una determinada entidad del
proyecto

|link:#apendice-comandos_addon-persistence_occchecksum_occ-checksum-all[occ
checksum all] |Establece un control de concurrencia optimista mediante
una suma de comprobación (checksum) para todas las entidades del
proyecto
|=======================================================================

occ checksum set
~~~~~~~~~~~~~~~~

Establece un control de concurrencia optimista mediante una suma de
comprobación (checksum) en una entidad del modelo. Si la entidad ya
tiene configurado este sistema de control, el comando no permitirá
sobreescribir su configuración y cualquier modificación deberá
realizarse sobre la anotación relacionada _@GvNIXEntityOCCChecksum_ que
se habrá incluido en la clase Java de la entidad.

Sus parámetros son:

--entity::
  _[Requerido si no está en el contexto] [Clase Java] [Autocompletado]_
  +
  Entidad sobre la que establecer el sistema de control de concurrencia
  optimista mediante una suma de comprobación (checksum).
--fieldName::
  _[Opcional] [Cadena]_
  +
  Nombre del campo de la entidad en donde almacenar la suma de
  comprobación (checksum). Habitualmente este parámetro no necesita ser
  establecido. Si no se especifica, tomará por convención el nombre
  _occChekcsum_ para dicha propiedad.
--digestMethod::
  _[Opcional] [Cadena]_
  +
  Método a utilizar en el cálculo de la suma de comprobación (checksum).
  Habitualmente este parámetro no necesita ser establecido. Los posibles
  valores vienen definidos por los algoritmos aceptados por
  http://docs.oracle.com/javase/1.5.0/docs/api/java/security/MessageDigest.html[MessageDigest.getInstance(String
  algorithm)]. Por defecto, se utilizará el algoritmo _md5_, pero pueden
  utilizarse otros como por ejemplo _sha_.

occ checksum all
~~~~~~~~~~~~~~~~

Estable un control de concurrencia optimista mediante una suma de
comprobación (checksum) en todas las entidades de la aplicación que no
la tuviesen todavía establecida. Cualquier modificación una vez
establecido el control deberá realizarse sobre la anotación relacionada
_@GvNIXEntityOCCChecksum_ que se habrá incluido en todas las clases Java
de entidad.

Sus parámetros son:

--fieldName::
  _[Opcional] [Cadena]_
  +
  Nombre del campo en cada entidad en donde almacenar la suma de
  comprobación (checksum). Habitualmente este parámetro no necesita ser
  establecido. Si no se especifica, tomará por convención el nombre
  _occChekcsum_ para dicha propiedad.
--digestMethod::
  _[Opcional] [Cadena]_
  +
  Método a utilizar en el cálculo de la suma de comprobación (checksum).
  Habitualmente este parámetro no necesita ser establecido. Los posibles
  valores vienen definidos por los algoritmos aceptados por
  http://docs.oracle.com/javase/1.5.0/docs/api/java/security/MessageDigest.html[MessageDigest.getInstance(String
  algorithm)]. Por defecto, se utilizará el algoritmo _md5_, pero pueden
  utilizarse otros como por ejemplo _sha_.

  //Return level title
  :leveloffset: 0
