Comandos del add-on Web MVC
---------------------------

Para una descripción detallada de las características del add-on
consultar la documentación del link:#addon-web-mvc[add-on Web MVC].

.Comandos de add-on Web MVC
[width="100%",cols="33%,67%",options="header",]
|=======================================================================
|Comando |Descripción
|link:#apendice-comandos_addon-web-mvc_mvc-batch_web-mvc-batch-setup[web
mvc batch setup] |Instala el soporte para la funcionalidad Web Batch

|link:#apendice-comandos_addon-web-mvc_mvc-batch_web-mvc-batch-add[web
mvc batch add] |Genera los métodos de de persistencia en bloque para un
controlador.

|link:#apendice-comandos_addon-web-mvc_mvc-batch_web-mvc-batch-all[web
mvc batch all] |Genera los métodos de de persistencia en bloque para
todos los controladores.

|[multiblock cell omitted] |[multiblock cell omitted]

|link:#apendice-comandos_addon-web-mvc_mvc-jquery_web-mvc-jquery-setup[web
mvc jquery setup] |Instala los artefacto necesario para usar vistas
usando la librería JavaScript jQuery.

|link:#apendice-comandos_addon-web-mvc_mvc-jquery_web-mvc-jquery-update-tags[web
mvc jquery update tags] |Actualiza los artefactos, ya instalados en el
add-on, por los actuales.

|link:#apendice-comandos_addon-web-mvc_mvc-jquery_web-mvc-jquery-add[web
mvc jquery add] |Convierte las vistas de un controlador a jQuery.

|link:#apendice-comandos_addon-web-mvc_mvc-jquery_web-mvc-jquery-all[web
mvc jquery all] |Convierte todas las vistas a jQuery.
|=======================================================================

web mvc batch setup
~~~~~~~~~~~~~~~~~~~

Instala las dependencias necesarias y configura el proyecto para dar
soporte a las peticiones de persistencia en bloque.

web mvc batch add
~~~~~~~~~~~~~~~~~

Añade los métodos al controlador para peticiones de persistencia en
bloque.

Sus parámetros son:

--controller::
  _[Requerido] [Clase controlador] [Autocompletado]_
  +
  Controlador destino.
--service::
  _[Opcional] [Clase de servicios de persistencia] [Autocompletado]_
  +
  Añade los métodos al todos los controladores para peticiones de
  persistencia en bloque.

web mvc batch all
~~~~~~~~~~~~~~~~~

Crea el servicio de persistencia en bloque para todas las entidades de
la aplicación.

web mvc jquery setup
~~~~~~~~~~~~~~~~~~~~

Instala los artefactos necesario para usar vistas que use la librería
jQuery.

web mvc jquery update tags
~~~~~~~~~~~~~~~~~~~~~~~~~~

Actualiza todos los artefactos necesario para que el add-on funcione.
Este comando es útil cuando se actualiza la versión del add-on y se
desea utilizar los cambios en los tagx u otros artefactos de la nueva
versión.

_Advertencia:_Al ejecutar este comando, _los artefactos del proyecto
serán reescritos_. Cualquier cambio sobre los originales se perderá. Por
lo tanto, es conveniente disponer de una _copia de seguridad o un
sistema de control de versiones_ para revisar las diferencias entre los
artefactos anteriores y la actualización.

web mvc jquery add
~~~~~~~~~~~~~~~~~~

Convierte las vistas de un controlador a jQuery.

Sus parámetros son:

--type::
  _[Requerido] [Clase controlador] [Autocompletado]_
  +
  Controlador cuyas vistas se desea convertir a jQuery.

web mvc jquery all
~~~~~~~~~~~~~~~~~~

Convierte las vistas de todos los controladores a jQuery.
