Mejoras de rendimiento
----------------------

//Push down level title
:leveloffset: 2

Descripción
-----------

En las aplicaciones generadas en algún caso pueden requerir la
implementación de alguna pequeña mejora para mejorar su rendimiento.

Las mejoras de rendimiento no serán siempre necesarias ya que dependen
de las características de la aplicación en desarrollo.

Patrones de conversión óptimos en el log
----------------------------------------

Se puede mejorar el rendimiento del sistema de log (log4j) evitando que
se muestre información innecesaria. Para ello modificar el fichero
_src/main/resources/log4j.properties_ modificando el _ConversionPattern_
del appender que esté utilizando la aplicación, por ejemplo
_log4j.appender.stdout.layout.ConversionPattern=_.

El _ConversionPattern_ adecuado depende del entorno en el que nos
encontremos. Será interesante disponer de mayor información en el log en
entornos de desarrollo aunque se reduzca algo el rendimiento y ofrecer
una menor información en los logs en entornos productivos. A
continuación se recomiendan unos valores adecuados para cada tipo de
entorno:

-----------------------------------------------------------------------------------------------------
Entornos de desarrollo e integración: %d{dd/MM/yyyy HH:mm:ss.SSS} [%t] %p %c{1}.%M(%L) | %m%n
Entornos de preproducción y producción: %d{dd/MM/yyyy HH:mm:ss.SSS} [%t] %p %c{1} | %m%n
-----------------------------------------------------------------------------------------------------

Los distintos valores en función del entorno se pueden establecer de
forma automática mediante el link:#_add_on_dynamic_configuration[add-on de
configuración dinámica].

Evitar la carga de listas de valores innecesarias
-------------------------------------------------

Las vistas (páginas jspx) y los controladores (clases Java) son
generadas con toda la información necesaria para que funcionen todas las
acciones de listado, creación, actualización, borrado, búsqueda, etc.
sobre una entidad.

En algunos casos, estas pantallas son personalizadas para ocultar campos
que no son necesarios. Esto es especialmente importante en el caso de
las relaciones con otras entidades y que se representan en página como
campos desplegables.

----------------------------------------------------
        ... field="propertyname" render="false" ...

----------------------------------------------------

En dicho caso es recomendable evitar que se carguen las listas de datos
que no se van a utilizar ya que realizan consultas a la base de datos
innecesarias. Para ello, se puede personalizar los métodos del
controlador llamados _populate_ y comentar aquellas líneas relacionadas
con el campo que se ha ocultado.

---------------------------------------------------------------------------------
        void populateEditForm(Model uiModel, Entity entity) {
        ...
        uiModel.addAttribute("propertyname", OtherEntity.findAllOtherEntities());
        ...
        }

---------------------------------------------------------------------------------

//Return level titles
:leveloffset: 0
