//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//
//   $ asciidoc -b html5 td-addon-jpa-historico_es.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 td-addon-jpa-historico_es.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf td-addon-jpa-historico_es.adoc

= {title}
:title:			Análisis y Prueba de Concepto histórico BBDD
:Project:   gvNIX, un Addon de Spring Roo Suite
:Copyright: 2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y Administración Pública - CC BY-NC-SA 3.0
:Author:    Dirección General de Tecnologías de la Información, Asociación gvSIG, DISID Corporation, S.L.
:corpsite:  www.gvnix.org
:doctype:   article
:keywords:  gvNIX, Documentation
:toc:
:toc-placement: left
:toc-title: Table of Contents
:toclevels: 4
:numbered:
:sectnumlevels: 4
:source-highlighter:  pygments
ifdef::backend-pdf[]
:pdf-style: asciidoctor
:pagenums:
:pygments-style:  bw
endif::[]

_2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y
Administración Pública - Generalitat Valenciana._ Esta obra está bajo la licencia
http://creativecommons.org/licenses/by-sa/3.0/es/[Reconocimiento-Compartir bajo la misma licencia 3.0 España]
de Creative Commons. Puede copiarla, distribuirla y comunicarla públicamente
siempre que especifique sus autores y comparta cualquier obra derivada bajo la
misma licencia.

[[descripcion-doc]]
== Descripción del documento

Documento de análisis y diseño técnico de una nueva funcionalidad de gvNIX que proporcione e integre el soporte de histórico de cambios en base de datos.

[[diseno]]
== Diseño técnico

Esta nueva funcionalidad se implementará dentro del add-on *addon-jpa* de gvNIX y se complementará con el desarrollo de auditoría de BBDD realizado anteriormente. En los siguientes apartados se desarrolla el diseño técnico de este add-on en lo que se refiere al sistema de histórico de cambios en BBDD.

[[analisis-solucion]]
=== Análisis de la solución

El histórico de base de datos consiste en guardar en tablas adicionales todos los cambios realizados en las entidades sobre las que se active el sistema de seguimiento de cambios.

Para llevar a cabo este proceso, será necesario que gvNIX modifique automáticamente la estructura de la aplicación del siguiente modo:

- Debe crear un sistema de proveedores de histórico que permitirá instalar distintas implementaciones para esta funcionalidad. Estos proveedores podrán ser dependientes de la implementación de JPA. Para esta versión, el proveedor de histórico que se implementará utilizará la librería _Hibernate Envers_.
- Se creará una clase servicio para recuperar el objeto que representa al usuario que realiza el cambio. El desarrollador personalizará esta clase para obtener los datos del usuario de la fuente adecuada (base de datos, petición, etc.). Los datos que proporcione esta clase se almacenarán como valor de usuario al actualizar las entidades.
* En el caso de utilizar Spring Security el add-on podrá generar una implementación por defecto basada en el uso de la interfaz _UserDetails_ de Spring Security.

[[analisis-funcional]]
=== Análisis funcional

Implementar la solución indicada en el punto anterior requiere actualizar/añadir los siguientes comandos gvNIX en el addon jpa:

- *jpa audit revisionLog*: Configura un proveedor de revisiones de histórico. Parámetros:
* provider (obligatorio): Proveedor de histórico a usar. Será autocompletado.


- *jpa audit add*: preparará el sistema de auditoría para una entidad. Parámetros:
* entity (obligatorio): Nombre de la clase de la entidad a auditar.
* listener (opcional): Clase que se encargará de monitorizar los cambios de la entidad. Si no se especifica, el nombre será el mismo que el nombre de la clase de la entidad con el sufijo _pass:[_auditListener]_.
* revisionLog (opcional): Registrar lista de revisiones en la entidad. Por defecto es null y este valor depende del proveedor de registro configurado (puede no haber).

- jpa audit all: preparará el sistema de auditoría para todas las entidades. Se usará el nombre por defecto para las clases de los listeners. Parámetros:
* package (opcional): Paquete java donde se generarán las clases de los listeners. Por defecto el mismo que las entidades.
* revisionLog (opcional): Registrar lista de revisiones para todas las entidades. Por defecto es null y este valor depende del proveedor de registro configurado (puede no haber).

[[diseno-tecnico]]
=== Diseño técnico

[[requisitos]]
==== Requisitos

1. El sistema de histórico de BBDD requiere que previamente se configure la persistencia en la aplicación, por lo que, los comandos indicados en el punto anterior no estarán visibles si antes no se ha ejecutado el comando *jpa setup*.

[[jpa-audit-revisionLog]]
==== jpa audit revisionLog

Nos apoyaremos en el siguiente ejemplo para explicar qué acciones realizará el comando en la aplicación:

	jpa audit revisionLog --provider NombreDeProveedor

Provocará los siguientes cambios:

- En aquellas entidades anotadas con _@GvNIXAudit_ que tengan establecido su atributo *revisionLog* a True se acutalizará su *.aj* para incluir:

* *static List<Visit> findAllVisit(Date)*: Devuelve la lista de entidades en la fecha solicitada
* *static List<Visit> findAllVisit(Long)*: Devuelve la lista de entidades en la revisión solicitada
* *static Visit findVisit(Long, Date)*: Devuelve el estado de la entidad en la fecha solicitada
* *static Visit findVisit(Long, Long)*: Devuelve el estado de la entidad en la revisión solicitada
* *static List<VisitRevison> findVisitInHistory(Long, Long, Map<String, Object>, List<String>, Integer, Integer)*: Búsqueda en el histórico (revisiones) con opciones de limitación de revisiones, filtro, ordenación y paginación
* *static List<VisitRevison> findVisitInHistoryByDates(Date, Date, Map<String, Object>, List<String>, Integer, Integer)*: Búsqueda en el histórico (revisiones) con opciones de limitación de fechas de revisión, filtro, ordenación y paginación
* *static Long getRevisionNumberForDate(Date)*: Devuelve la revisión corespondiente a una fecha
* *static List<VisitRevison> getVisitHistory(Long, Date, Date, Integer, Integer)*: Devuelve el histórico (revisiones) de un elemento (en base a su id) entre fechas de revisión con paginación:
* *List<VisitRevison> getThisVisitHistory(Date, Date, Integer, Integer)*: Devuelve el histórico (revisiones) de un elemento (de la instancia actual) entre fechas de revisión con paginación:
* Clase estática VisitRevison, que representa la información de la revisión de una instancia de la entidad, con los siguiente métodos:

** Visit getItem()
** Date getRevisionDate()
** Long getRevisionNumber()
** getRevisionUser()
** String getType()
** boolean isCreate()
** boolean isDelete()
** boolean isUpdate()


Si _@GvNIXAudit_ no tiene establecido el valor de _revisionLog_ el proveedor dispondrá de un método que informará el valor por defecto para ello.

[[jpa-audit-add]]
==== jpa audit add

Se mantiene la funcionalidad desarrollada para la auditoría (ver petición ENT-22554), pero se aplican las siguientes modificaciones:

- Al anotar la entidad con _@GvNIXAudit_ se incluye el parámetro revisionLog con el proveedor seleccionado.

[[jpa-audit-all]]
==== jpa audit all

Se mantiene la funcionalidad desarrollada para la auditoría (ver petición ENT-22554), pero se aplican las siguientes modificaciones:

- Al anotar las entidades con _@GvNIXAudit_ se incluye el parámetro revisionLog con el proveedor seleccionado.

[[implementacion-revisionLogProvider]]
=== Implementación de RevisionLogProvider

Interfaz que deben cumplir los proveedores de gestión de registro.

Las clases que implementen este interfaz deben estar anotadas con _@Component_ y _@Service_ de OSGi para que puedan ser registradas en el add-on.

Debe incluir los siguientes métodos:

- *boolean isAvailable()*: Informa si el proveedor puede ser usado en el proyecto actual

- *boolean isActive()*: Informa si el proveedor es el configurado actualmente

- *String getId()*: Identificador del proveedor

- *String getDescription()*: Descripción del proveedor

- *boolean getDefaultValueOfRevisionLogAttribute()*: Devuelve un booleano que indica que valor que se debe asumir para el `revisionLog` de las anotaciones cuyo valor sea `null`.

- *void setup()*: Realizar las operaciones necesaria para instalarse en el proyecto actual
