Add-on Web MVC Binding
----------------------

//Push down level title
:leveloffset: 2


Descripción
-----------

El add-on permite registrar ciertos editores de propiedades en Spring
MVC para uno o todos los controladores del proyecto.

Los editores son una pieza más de la arquitectura de Spring MVC. Se
encargan de controlar el modo en que las cadenas enviadas por el
navegador cliente, por ejemplo desde un formulario, se convierten en
objetos al llegar al servidor.

Para obtener más información sobre los editores de propiedades ver la
http://static.springsource.org/spring/docs/3.1.x/spring-framework-reference/html/validation.html#beans-beans-conversion[sección
de conversión de beans] de la documentación de Spring.

El comando
link:#_web_mvc_binding_stringtrimmer[web mvc
binding stringTrimmer] permite registrar un editor especialmente útil.
Este editor elimina los espacios en blanco al principio y al final de
las cadenas y además permite transformar las cadenas vacías en valores
nulos.

Este editor es especialmente interesante al realizar mantenimientos de
valores almacenados en bases de datos. Por defecto, cuando se deja vacío
un valor de un formulario y está relacionado con una columna de base de
datos del tipo cadena, al almacenar se escribe una cadena vacía. En
estos casos puede suele ser más interesante almacenar un valor nulo.

-----------------------------------------------------------------------------------------
roo>
Updated SRC_MAIN_JAVA/org/gvnix/test/web/EntityController.java
Updated ROOT/pom.xml added dependency org.gvnix:org.gvnix.web.mvc.binding.roo.addon:X.Y.Z
Created SRC_MAIN_JAVA/org/gvnix/test/web/EntityController_Roo_GvNIXStringTrimmerBinder.aj
-----------------------------------------------------------------------------------------

Al ejecutar el comando, el add-on incluirá la anotación
@GvNIXStringTrimmerBinder en la clase controladora especificada en el
parámetro _--class_ del comando o en todas las clases controladoras del
proyecto si no se especificó dicho parámetro. El parámetro
_--emptyAsNull_ por defecto toma el valor _true_ indicando que las
cadenas vacías deben convertirse en valores nulos.

---------------------------------------------
...
@GvNIXStringTrimmerBinder(emptyAsNull = true)
public class EntityController {
}
---------------------------------------------

Esto generará en un aspecto Java propio todo el código necesario para
registrar el editor, representado en Spring MVC mediante la clase
http://static.springsource.org/spring/docs/3.1.x/javadoc-api/org/springframework/beans/propertyeditors/StringTrimmerEditor.html[StringTrimmerEditor].

---------------------------------------------------------------------------------
privileged aspect EntityController_Roo_GvNIXStringTrimmerBinder {

    @InitBinder
    public void EntityController.initStringTrimmerBinder(WebDataBinder binder) {
        binder.registerCustomEditor(String.class, new StringTrimmerEditor(true));
    }

}
---------------------------------------------------------------------------------

Es interesante resaltar que este método puede ser reutilizado haciendo
push-in para registrar cualquier editor asociado a un tipo de datos
adecuado, como se hace en el ejemplo anterior asociando _String_ con
_StringTrimmerEditor_.

Para obtener mas detalles sobre el comando ver el
link:#_comandos_del_add_on_web_mvc_binding[apéndice de comandos] de
este add-on.

Futuras versiones
-----------------

* Para futuras versiones este add-on permitirá registrar más editores de
entre los enumerados en la Tabla 5.2 de la
http://static.springsource.org/spring/docs/3.1.x/spring-framework-reference/html/validation.html#beans-beans-conversion[documentación
de Spring].

//Return level title
:leveloffset: 0
