Add-on Campos Lupa
------------------

//Push down level title
:leveloffset: 2


Implementación de campos lupa en el proyecto gvNIX.

Descripción
-----------

Este add-on permite utilizar componentes de tipo lupa en aplicaciones
gvNIX. Gracias a estos componentes, podemos buscar registros de forma
sencilla de campos relacionados sin tener que visualizar todos los datos
en un desplegable.

Instalación del componente lupa
-------------------------------

Para instalarlo, hay que utilizar el comando
link:#_web_mvc_loupe_setup[web mvc loupe setup],
el cual solo estará disponible después de instalar el
link:#_comandos_del_add_on_web_mvc[add-on
JQuery] en nuestro proyecto.

Permitiendo a una entidad utilizar el campo lupa
------------------------------------------------

Una vez instalados todos los componentes, es necesario generar una serie
de métodos para realizar las búsquedas y la visualización de los
resultados. Para que el controlador disponga de estos métodos,
utilizaremos el comando
link:#_web_mvc_loupe_set[web mvc loupe set] sobre
el controlador seleccionado.

Utilizando componentes lupa
---------------------------

Ahora que el Controlador ya dispone de los métodos necesarios,
ejecutaremos el comando
link:#_web_mvc_loupe_field[web mvc loupe field]
sobre el field de la entidad a la que pertenece el controlador con los
métodos generados. Una vez ejecutado este comando, transformaremos el
campo indicado a un campo de tipo lupa en la capa web de nuestra
aplicación.

Actualizando componentes lupa
-----------------------------

Para mantener actualizados los componentes importados mediante el
comando de instalación, podemos ejecutar el comando
link:#_web_mvc_loupe_update[web mvc loupe
update].

Apendice de comandos
--------------------

Para ver con mas detalle el comando que proporciona el add-on consultar
la sección de link:#_comandos_del_add_on_web_mvc_lupa[comandos del
add-on Lupa].

//Return level title
:leveloffset: 0
