//Push down level title
:leveloffset: 2


Implementación de campos lupa en el proyecto gvNIX.

Descripción
-----------

Este add-on permite utilizar componentes de tipo lupa en aplicaciones gvNIX. Gracias a estos componentes, podemos buscar registros de forma sencilla de campos relacionados sin tener que visualizar todos los datos en un desplegable.

Al aplicar este add-on sobre un proyecto, en los formularios es posible seleccionar registros de campos relacionados de una entidad. Estos registros son mostrados en una lista dinámica según las coincidencias de carácteres del texto introducido o en la lista completa de los registros de este campo.

El addon permite configurar la representación de registros a mostrar , permitiendo limitar el número máximo de registros, los campos campo por los que se buscará coincidencias, los campos de la entidad relacionada que se mostrarán en cada resultado, filtros personalizados de búsqueda, etc.

Instalación del componente lupa
-------------------------------

Para instalarlo, hay que utilizar el comando
link:#_web_mvc_loupe_setup[web mvc loupe setup],
el cual solo estará disponible después de instalar el
link:#_comandos_del_add_on_web_mvc[add-on
JQuery] y el link:#_add_on_web_mvc_datatables[add-on Web
MVC Datatables] en nuestro proyecto.

Permitiendo a una entidad utilizar el campo lupa
------------------------------------------------

Una vez instalados todos los componentes, es necesario generar una serie
de métodos para realizar las búsquedas y la visualización de los
resultados. Para que el controlador disponga de estos métodos,
utilizaremos el comando
link:#_web_mvc_loupe_set[web mvc loupe set] sobre
el controlador seleccionado.

Utilizando componentes lupa
---------------------------

Ahora que el Controlador ya dispone de los métodos necesarios,
ejecutaremos el comando
link:#_web_mvc_loupe_field[web mvc loupe field]
sobre el field de la entidad a la que pertenece el controlador con los
métodos generados. Una vez ejecutado este comando, transformaremos el
campo indicado a un campo de tipo lupa en la capa web de nuestra
aplicación.


[IMPORTANT] 
El controlador de la entidad a la que referencia el campo también debe tener 
instalado link:#_add_on_web_mvc_datatables[Datatables] con un modo de 
visualización de listado estándar para la correcta visualización del 
componente lupa. Si se desea instalar Datatables con un modo no estándar 
(mode="show", por ejemplo), se puede crear un controlador adicional para la 
misma entidad con el modo estándar de Datatables y asignar el atributo 
"listPath" del campo lupa a la vista "list" de este segundo controlador. 
El atributo "listPath" se explica en la sección 
link:#_configuración_del_widget_lupa["Configuración del widget lupa"].

Actualizando componentes lupa
-----------------------------

Para mantener actualizados los componentes importados mediante el
comando de instalación, podemos ejecutar el comando
link:#_web_mvc_loupe_update[web mvc loupe
update].

Apendice de comandos
--------------------

Para ver con mas detalle el comando que proporciona el add-on consultar
la sección de link:#_comandos_del_add_on_web_mvc_lupa[comandos del
add-on Lupa].

Configuración del widget lupa
-----------------------------

Este addon permite mostrar el componente lupa en las diferentes *jspx* mediante el fichero _loupe.tagx_, el cual es añadido al proyecto al instalar el addon. Este fichero contiene una serie de propiedades para definir las opciones de configuración del componente, como por ejemplo *max*, que permite limitar el número de resultados a mostrar. Para obtener más información sobre estos parámetros consultar el fichero _WEB-INF/tags/loupefield/loupe.tagx_ donde estos parámetros incluyen una descripción en su definición.

Ejemplo:
[source,xml]
----
<form:create id="fu_com_springsource_petclinic_domain_Pet" modelAttribute="pet" path=" /pets" 
    render="${empty dependencies}" z="E4jWxGSZUphUG7qjB1vBKbchssY=">
  <field:input field="name" id="c_com_springsource_petclinic_domain_Pet_name" min="1" 
    required="true" z="xqcX/Hnb52FNxMLXqv1yGlbMUM="/>
  <loupefield:loupe returnFields="telephone" searchField="city" hiddeUtilbox="false" 
    modalWidth="400" required="true" baseFilter="city=Valencia" additionalFields="lastName,city" 
    max="4" caption="firstName" field="owner" controllerPath="pets" 
    id="c_com_springsource_petclinic_domain_Pet_owner" listPath="owners/list" mode="update" 
    pkField="id" z="user-managed"/>
</form:create>
----

* *field* debe ser el campo del objeto expuesto en el formulario que se quiere representar en el campo lupa.
* *required* indica si este campo es obligatorio (el valor por defecto es false).
* *listPath* ruta a la lista del selector.
* *controllerPath* ruta relativa al controller de la entidad a la que pertenece la vista.
* *pkField* es el campo de la clave primaria de la entidad de referencia en el campo lupa. Se utiliza para realizar las búsquedas.
* *caption* campos de la entidad se mostrarán en el campo lupa cuando se elige un resultado. Deben estar separados por comas.
* *additionalFields* campos adicionales de la entidad por los que se buscarán coincidencias. Si no se especifica ninguno, se buscará por id.
* *baseFilter* filtros por defecto por los que se mostrarán resultados. En el ejemplo sólo se mostrarán owners cuya ciudad es valencia.
* *modalWidth* anchura del diálogo modal, en píxeles (el valor por defecto es 800).
* *hiddeUtilbox* especifica si ocultar elementos con la clase utilbox (el valor por defecto es true).
* *searchField* especifica el campo usado para buscar (en el filtro de diálogo) cuando el input pierde el foco (por defecto es el primer campo de caption).
* *returnFields* campos adicionales que devolverá la búsqueda de Ajax, pero por los que no se buscará. Deben estar separados por comas.

//Return level title
:leveloffset: 0
