Add-on Web Dialog
-----------------

//Push down level title
:leveloffset: 2


Add-on para la gestión de excepciones no controladas y de mensajes de
usuario.

Descripción
-----------

Este add-on permite gestionar las excepciones no controladas en el
código de la aplicación y así mostrar mensajes inteligibles al usuario
en una ventana modal (pop-up) y en el idioma actual de la aplicación sin
necesidad de realizar ningún desarrollo en la capa web.

El add-on, al aplicarse sobre un proyecto, por defecto configura ciertas
excepciones que serán visualizadas de forma amigable al usuario en el
caso de no ser gestionadas directamente desde la aplicación. Así mismo,
se pueden incluir nuevas excepciones y modificar los textos amigables
que se mostrarán en lugar de la excepción para cada idioma disponible en
la aplicación.

Durante su aplicación se instalan algunas cadenas, tanto en ingles como
en castellano, para mostrar mensajes para los errores de conversión de
datos numéricos y fechas.

El add-on también permite mostrar mensajes de usuario sin realizar
ninguna implementación en la capa web mediante la invocación de métodos
desde el controlador que son los encargados de mostrar dichos mensajes
en la pantalla del usuario.

Los mensajes de excepción y de usuario se muestran en un diálogo o
ventana modal. Se permite además la modificación de las ventanas modales
de excepción y de mensaje de usuario para que puedan ser personalizadas
de acuerdo a los requerimientos que sean necesarios.

Instalación
-----------

Para aplicar esta funcionalidad sobre un proyecto se debe ejecutar en
primer lugar el comando link:#_web_mvc_dialog_setup[web mvc
dialog setup]. Al hacerlo se incluye el soporte para diálogos modales en
la aplicación.

El componente visual _message-box.tagx_ que instala el add-on es el
encargado de mostrar en pantalla un diálogo modal al usuario.

Al mismo tiempo, la ejecución de este comando configura una serie de
excepciones que serán mapeadas con sus respectivos diálogos modales y
mensajes amigables en múltiples idiomas. En las siguiente secciones se
verá más detalladamente las excepciones controladas y el uso de los
diálogos modales.

Excepciones controladas por gvNIX
---------------------------------

Conjunto de excepciones inicialmente definidas y controladas por gvNIX
al ejecutar el comando _web mvc dialog setup_.

* java.sql.SQLException.
+
Se ha producido un error en el acceso a la base de datos.
* java.io.IOException.
+
Existen problemas para enviar o recibir datos.
* org.springframework.transaction.TransactionException.
+
Se ha producido un error en la transacción. No se han guardado los datos
correctamente.
* java.lang.UnsupportedOperationException.
+
Se ha producido un error no controlado.
* javax.persistence.OptimisticLockException.
+
No se puede actualizar el registro debido a que ha sido actualizado
previamente.

Las excepciones se muestran mediante un dialogo modal. Para ello, se
modifica la definición, en el archivo webmvc-config.xml, del bean
_SimpleMappingExceptionResolver_ reemplazando la clase que se define por
una propia. La clase propia se encontrará instalada en el proyecto en la
clase _MessageMappingExceptionResolver.java_ del subpaquete
_web.servlet.handler_. En el subpaquete _web.dialog_ se instala también
la clase _Dialog.java_, la cual es un bean que representa la información
necesaria para visualizar una excepción en la ventana modal renderizada
por el componente _message-box.tagx_.

Añadir nuevas excepciones a la gestión
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Pasos a seguir para incluir en la gestión automática de excepciones de
la aplicación una nueva excepción.

El Add-on proporciona ciertos comandos que permiten realizar de forma
automática las siguientes operaciones para la gestión de excepciones:

1.  Añadir el control de una excepción a la aplicación:
* Define la excepción a capturar en el bean
_messageMappingExceptionResolverBean_ del archivo _webmvc-config.xml_.
* Asocia una dirección a la excepcion en un nuevo bean
_<mvc:view-controller>_ en el archivo _webmvc-config.xml_.
* Crea la nueva jspx asociada a la excepción.
* Instancia la jspx creada en el archivo _views.xml_ en el directorio
_WEB-INF_ la aplicación.
* Crear las etiquetas multi idioma en los ficheros de propiedades de
todos los idiomas que estén instalados en la aplicación.
2.  Mostrar las excepciones gestionadas por la aplicación:
* Muestra la lista de excepciones definidas en el bean
_messageMappingExceptionResolver_ del archivo _webmvc-config.xml_.
3.  Eliminar excepciones controladas por la aplicación:
* Elimina del fichero _webmvc-config.xml_ las referencias a la excepción
y por lo tanto la quita de las excepciones gestionadas por la
aplicación.
* Elimina la página jspx asociada.
* Elimina las referencias a la excepción en el archivo views.xml.

Para obtener más información sobre estos comandos de gestión de
excepciones consultar el apendice
link:#_comandos_del_add_on_web_dialog[Comandos del Add-on Web
Dialog].

Nuevos diálogos modales
-----------------------

Estos diálogos son útiles para mostrar mensajes al usuario informando de
cualquier circunstancía tras una operación determinada.

Para aplicar esta funcionalidad sobre el proyecto primero se debe haber
ejecutado el comando
link:#_web_mvc_dialog_setup[web mvc
dialog setup].

El comando
link:#_web_mvc_dialog_add[web mvc
dialog add] añade la anotación 'GvNIXModalDialogs' en la clase
controladora que se le indica.

-----------
roo-gvNIX>
-----------

La anotación generará dos métodos asociados con el controlador. Un
método con el nombre _modalDialog_ y otro que tomará como nombre el
valor del parámetro _name_ del comando y una página jspx en
_WEB-INF/dialogs_ con también el mismo nombre.

El método _modalDialog_ permite al desarrollador mostrar diálogos
modales genéricos en la parte visual directamente desde el código Java
del controlador. Para ello, el desarrollador proporcionará un título,
una descripción y un tipo de mensaje que será mostrado en la página al
usuario. La signatura del método es:

--------------------------------------------------------------------
modalDialog(DialogType dialogType, String title, String description,
            HttpServletRequest httpServletRequest)
--------------------------------------------------------------------

El segundo método servirá para mostrar un mensaje específico. La
diferencia principal es que este nuevo método tiene su propia página
jspx asociada y además permite proporcionar parámetros adicionales a
dicha página, cosa que no permite el método _modalDialog_.

----------------------------------------------------------------------------------
petsdialog(DialogType dialogType, String title, String description,
            HashMap<String, Object> params, HttpServletRequest httpServletRequest)
----------------------------------------------------------------------------------

Asociado a este método también se habrá creado en _WEB-INF/dialogs_ una
página jspx con el nombre _petsdialog.jspx_ que podrá personalizarse
según las necesidades. El Map _params_ será proporcionado a la página y
por lo tanto el desarrollador puede insertar valores desde el
controlador para utilizarlos en el diálogo.

Los parámetros de cada uno de los dos métodos anteriores definen la
siguiente información:

dialogType::
  es un tipo enumerado que puede tomar como valores: Error, Info, Alert,
  Suggest. Cada uno define un nivel de severidad en el diálogo y
  producirá en el aspecto visual del diálogo que aparezca con distinto
  color e icono.
title::
  es el código del recurso i18n que se usará como título del diálogo
  modal.
description::
  es el código del recurso i18n que se usará como descripción del
  diálogo modal.
params::
  es un Map que se puede utilizar para proporcionar tantos parámetros
  como sea necesario al componente visual del diálogo modal para
  confeccionarlo y mostrar en él cualquier información necesaria.
httpServletRequest::
  este parámetro se usa internamente en el método para obtener la sesión
  del usuario y establecer un atributo que será leido por el componente
  message-box.tagx para mostrar el diálogo. Si al invocar el método no
  se dispone de este parámetro, se puede obtener añadiendo el parámetro
  _HttpServletRequest httpServletRequest_ a los parámetros del método
  que contiene la invocación (esta es una característica especial de los
  métodos que gestionan las URLs en Spring MVC y que permite declarar
  distintos parámetros de entre algunos dados).

Ejemplos de dialogos personalizados
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Con este nuevo soporte para crear diálogos modales gvNIX ofrece una gran
libertad para maquetar multitud de mensajes de usuario o diálogos de la
aplicación (avisos, errores, mensajes de confirmación, formularios,
etc.).

A continuación se muestra una pequeña demostración de implementación de
algunos de estos mensajes personalizados.

.Mensaje de aviso de aplicación

En ocasiones puede ser necesario que tras una acción (una petición al
servidor) se muestre en la respuesta algún mensaje acerca del resultado
de la operación solicitada o, en el caso de pantallas de búsqueda,
indicar que no se han encontrado resultados.

Con el soporte de este add-on se puede incluir la siguiente línea de
código en cualquier punto de un método de un controlador para definir un
mensaje informativo.

-----------------------------------------------------------------------------
modalDialog(DialogType.Info, "message_info_title", "message_description_key",
                httpServletRequest);
-----------------------------------------------------------------------------

.Mensaje de confirmación

Puede ser necesario que tras una acción, la aplicación deba preguntar si
se desea ir a una página en concreto. A continuación se verán los pasos
y cambios en el código de un controlador para definir este mensaje de
confirmación.

En el ejemplo, se va a añadir a la aplicación de ejemplo petclinic un
mensaje de confirmación que consultará al usuario si quiere ir al
formulario de mascotas (Pets) tras actualizar la información de un
propietario (Owner).

1.  Añadir un diálogo modal a la aplicación mediante "_web mvc dialog
message add_"
+
---------------------------------------------------------------------
web mvc dialog add --class ~.web.OwnerController --name confirmgopets
---------------------------------------------------------------------
+
Esto generará un método _confirmgopets_ disponible en _OwnerController_
y una jspx base llamada _confirmgopets_ en _WEB-INF/dialogs_ que será
personalizada.
2.  Modificar el método _update_ de _OwnerController_ para añadir la
llamada al método _confirmgopets_ justo antes de la línea de _return_.
Para ello se debe llevar el método _update_ desde
_OwnerController_Roo_Controller.aj_ hasta _OwnerController.java_,
podemos usar la opción push-in que ofrece Eclipse. Una vez movido el
método, será modificado quedando como sigue:
+
------------------------------------------------------------------------------------
@RequestMapping(method = RequestMethod.PUT, produces = "text/html")
public String update(@Valid Owner owner, BindingResult bindingResult, Model uiModel,
        HttpServletRequest httpServletRequest) {
    if (bindingResult.hasErrors()) {
        populateEditForm(uiModel, owner);
        return "owners/update";
    }
    uiModel.asMap().clear();
    owner.merge();



    return "redirect:/owners/" + encodeUrlPathSegment(owner.getId().toString(),
            httpServletRequest);
}
------------------------------------------------------------------------------------
+
Se ha resaltado en negrita la parte específica que ha de modificarse
para mostrar el diálogo modal.
+
El HashMap _dialogParams_ permite proporcionar al componente
message-box.tagx información adicional para mostrarla o utilizarla como
sea necesario. En este caso, es necesario indicar a qué página dirigir
al usuario en caso de que responda afirmativamente a la pregunta de
confirmación, pero se podría definir cualquier tipo de parámetro, desde
un String hasta objetos del Modelo de la aplicación o listas de objetos.
3.  Modificar la jspx que ha creado el add-on (confirmgopets.jspx) para
adecuarla a las necesidades del proyecto:
+
----------------------------------------------------------------------------------
<div xmlns:c="http://java.sun.com/jsp/jstl/core"
                    xmlns:util="urn:jsptagdir:/WEB-INF/tags/util"
                    xmlns:fn="http://java.sun.com/jsp/jstl/functions"
                    xmlns:spring="http://www.springframework.org/tags"
                    xmlns:jsp="http://java.sun.com/JSP/Page" version="2.0">
  <jsp:directive.page contentType="text/html;charset=UTF-8" />
  <jsp:output omit-xml-declaration="yes" />
  <spring:message var="title" code="${titleCode}" text="Message title"
        htmlEscape="false" />
  <util:panel id="title" title="${title}">
    <h2>${fn:escapeXml(title)}</h2>
    <p>
     <spring:message code="${descriptionCode}"
            text="This is the dialog description ..." htmlEscape="false"/>
    </p>
    <div class="closeMessage">
     <spring:message var="closeButtonValue" code="button_close"/>
     <button class="boton" dojoType="dijit.form.Button" type="button"
       onClick="dijit.byId('${dialogId}').hide();">${closeButtonValue}</button>
      <spring:url value="" var="locationUrl"/>
      <spring:message var="confirmButtonValue" code="confirmButtonValue"/>
      <button class="boton" dojoType="dijit.form.Button" type="button"
        onClick="location.href = '${locationUrl}';">${confirmButtonValue}</button>
    </div>
  </util:panel>
</div>
----------------------------------------------------------------------------------
+
En este caso se ha resaltado el accesso al HashMap de parámetros del
diálogo (dialogParams) para demostrar el modo en que se debe extraer los
datos que le llegan al diálogo desde el controlador.

.Diálogo modal con formulario

En alguna ocasión puede ser necesario mostrar un formulario en un
diálogo modal para solicitar información al usuario, siguiendo el
ejemplo anterior, se debería modificar la jspx que crea el add-on para
incluir un formulario. En este ejemplo, tras crear un nuevo Owner en la
aplicación, se mostrará un formulario para que cree su primera mascota.

1.  Añadir un diálogo modal a la apliacaión mediante "_web mvc dialog
message add_"
+
------------------------------------------------------------------------
web mvc dialog add --class ~.web.OwnerController --name createPetInModal
------------------------------------------------------------------------
+
Esto genera un método _createPetInModal_ disponible en _OwnerController_
y una jspx base llamada _createPetInModal_ en _WEB-INF/dialogs_ que será
personalizada.

2.  Modifica el método create de OwnerController. Al igual que en el
ejemplo anterior debemos hacer el Push-in del método. Lo modificamos
para que quede como se muestra:
+
------------------------------------------------------------------------------------
@RequestMapping(method = RequestMethod.POST, produces = "text/html")
public String create(@Valid Owner owner, BindingResult bindingResult, Model uiModel,
        HttpServletRequest httpServletRequest) {
    if (bindingResult.hasErrors()) {
        uiModel.addAttribute("owner", owner);
        addDateTimeFormatPatterns(uiModel);
        return "owners/create";
    }
    uiModel.asMap().clear();
    owner.persist();



    return "redirect:/owners/" + encodeUrlPathSegment(owner.getId().toString(),
            httpServletRequest);
}
------------------------------------------------------------------------------------

3.  Modificar la jspx incluyendo el formulario de creación de mascotas
(Pets):
+
-------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<div xmlns:c="http://java.sun.com/jsp/jstl/core"
        xmlns:field="urn:jsptagdir:/WEB-INF/tags/form/fields"
        xmlns:form="urn:jsptagdir:/WEB-INF/tags/form"
        xmlns:jsp="http://java.sun.com/JSP/Page"
        xmlns:spring="http://www.springframework.org/tags"
        version="2.0">
    <jsp:directive.page contentType="text/html;charset=UTF-8"/>
    <jsp:output omit-xml-declaration="yes"/>


    <form:create id="fc_com_springsource_petclinic_domain_Pet" modelAttribute="pet"
            path="/pets" render="${empty dependencies}" z="lgvEyAlAYOudDmaPjwU0ABseTIk=">
        <field:checkbox field="sendReminders"
                id="c_com_springsource_petclinic_domain_Pet_sendReminders"
                z="uPpMX+IWb0KONpvd11fpG8x4/4Q="/>
        <field:input field="name" id="c_com_springsource_petclinic_domain_Pet_name"
                min="1" required="true" z="ZY+k75JeSo9RmejYZRFNIvs2aBg="/>
        <field:input field="weight" id="c_com_springsource_petclinic_domain_Pet_weight"
                min="0" required="true" validationMessageCode="field_invalid_number"
                z="cOD5zE/z7gy+RZu5kVSPuxCa+/I="/>
        <input type="hidden" id="c_com_springsource_petclinic_domain_Pet_owner"
                name="owner" value="${owner.id}" />
        <field:select field="owner" id="c_com_springsource_petclinic_domain_Pet_owner"
                itemValue="id" items="${owners}" path="/owners" render="false"
                z="fGzswAP4XXvhPhowJKsRVve929c="/>
        <field:select field="type" id="c_com_springsource_petclinic_domain_Pet_type"
                items="${pettypes}" path="pettypes" required="true"
                z="+hDCnUp+Y+A1RlT+AjH07sgipOo="/>
    </form:create>
    <form:dependency dependencies="${dependencies}"
            id="d_com_springsource_petclinic_domain_Pet" render="${not empty dependencies}"
            z="kThDNIW+69h9nI/69ynY1WyUieo="/>
</div>
-------------------------------------------------------------------------------------------

Futuras versiones
-----------------

Mejoras a incluir en futuras versiones del add-on.

* Obtención de las excepciones y los mensajes multi idioma de las
excepciones no controladas que deben visualizarse de forma amigable
desde una base de datos en la que se encuentra almacenada dicha
información. Así podría definirse un repositorio central de excepciones
para múltiples aplicaciones y sus mensajes amigables.
* Envío de un informe por email al responsable de la aplicación con
información detallada cuando se ha producido una excepción.

//Return level title
:leveloffset: 0
