Comandos del add-on Web MVC Binding
-----------------------------------

//Push down level title
:leveloffset: 2


Para una descripción detallada de las características del add-on
consultar la documentación del link:#_add_on_web_mvc_binding[add-on Web
MVC Binding].

.Comandos del add-on Web MVC Binding
[width="100%",cols="33%,67%",options="header",]
|=======================================================================
|Comando |Descripción
|link:#_web_mvc_binding_stringtrimmer[web mvc
binding stringTrimmer] |Registra el StringTrimmerEditor.
|=======================================================================

web mvc binding stringTrimmer
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Configura en un controlador concreto o en todos los controladores del
proyecto un editor de propiedades para cadenas que elimina espacios al
inicio y al fin y opcionalmente permite transformar cadenas vacías a
valores nulos.

Sus parámetros son:

--class::
  _[Opcional] [Clase Java] [Autocompletado]_
  +
  Nombre de la clase Java controladora en la que registrar el editor. Si
  no se indica este parámetro, se registrará el editor en todos los
  controladores del proyecto.
--emptyAsNull::
  _[Opcional] [Booleano] [Autocompletado]_
  +
  Indica si las cadenas vacias deben convertirse en valores nulos.

//Return level title
:leveloffset: 0
