Buscadores de entidades
-----------------------

//Push down level title
:leveloffset: 2


En la sección de recetas se puede encontrar información adicional para
link:#_desarrollo_de_buscadores_con_gran_cantidad_de_campos[desarrollar buscadores con gran
cantidad de campos] y también para hacer los
link:#_campos_opcionales_en_los_buscadores[campos opcionales en los buscadores] .

Descripción
-----------

Roo permite generar buscadores sobre cualquier entidad del
modelo de la aplicación mediante el comando
http://docs.spring.io/spring-roo/docs/2.0.0.BUILD-SNAPSHOT/reference/html/#finder-add[finder
add]. El comando espera el nombre del buscador a generar en un formato
determinado. Para conocer el formato se puede utilizar como ayuda el
comando
http://docs.spring.io/spring-roo/docs/2.0.0.BUILD-SNAPSHOT/reference/html/#finder-list[finder
list].

En los siguientes puntos se muestra un ejemplo de como elegir y generar
un buscador sobre una de las entidades del proyecto del script de
ejemplo _clinic.roo_ que viene incluido con el framework. Se utilizará
la entidad Owner para generar un buscador sobre ella.

Listar buscadores
-----------------

Ejecutar el comando finder list sobre la entidad Owner

-------------------------------------------------------------------------
roo>
        ...
        findOwnersByLastNameLikeAndCityLike(String lastName, String city)
        ...
-------------------------------------------------------------------------

En el comando se indica la entidad sobre la que se desea consultar sus
buscadores con _--class_. El resto de parámetros son opcionales. El
parámetro _--depth_ indica el nivel de profundidad a tener en cuenta, es
decir la cantidad de propiedades a combinar en el buscador. Debido a la
enorme cantidad de combinaciones de propiedades que puede existir para
una entidad, está limitado a un máximo de 3. El parámetro _--filter_
aplica un filtro de forma que solo se mostrarán los posibles buscadores
que contengan la cadena indicada.

El comando devuelve una lista de resultados con todos los posibles
buscadores que coinciden con los términos de búsqueda, de entre ellos se
va a escoger findOwnersByLastNameLikeAndCityLike que genera un buscador
para la entidad Owners cuyo _lastName_ y _city_ contenga la cadena que
se le pase como parámetro respectivamente, ambas utilizando para ello el
operador _like_.

Consultar la documentación del comando
http://docs.spring.io/spring-roo/docs/2.0.0.BUILD-SNAPSHOT/reference/html/#finder-list[finder
list] para más información.

Creación de un buscador
-----------------------

Es importante resaltar que no es necesario utilizar el comando _finder
list_ antes de utilizar el comando _finder add_. Una vez conocida la
nomenclatura utilizada para definir los buscadores no es complicado
definir directamente el nombre del buscador deseado. A continuación, se
muestra una pequeña guía con el formato que sigue la definición del
nombre de un buscador:

------------------------------------
findEntitiesByPropertyFilterOperator
------------------------------------

* Entities: Nombre de la entidad sobre la que generar el buscador. Su
nombre debe ser escrito en plural, utilizando para su pluralización las
normas del lenguage Inglés. Por ejemplo, la entidad _Entity_ tomará como
plural _Entities_.
* La porción del buscador _PropertyFilter_ puede repetirse tantas veces
como propiedades se desee añadir al filtro siempre y cuando se utilice
un _Operator_ para separar el filtro sobre una propiedad y el siguiente.
** Property: Nombre de la propiedad de la entidad a incluir como filtro
en el buscador. Debe tener el mismo nombre que la propiedad definida en
la entidad, pero comenzando por mayúscula.
** Filter: Tipo de filtro a aplicar sobre la propiedad anterior de entre
los siguientes posibles valores en función del tipo de dato de la
propiedad.
*** Cadenas (String, ...): Equals, IsNotNull, IsNull, Like, NotEquals.
*** Numéricos (Float, Integer, Long, ...): Between, Equals, GreaterThan,
GreaterThanEquals, IsNotNull, IsNull, LessThan, LessThanEquals,
NotEquals.
*** Fechas (Date, Calendar, ...): Between, Equals, GreaterThan,
GreaterThanEquals, IsNotNull, IsNull, LessThan, LessThanEquals,
NotEquals.
*** Booleanos (Boolean, ...): Not.
*** Enumerados (Enum, ...): No aplica. El filtro ya viene definido por
el valor de la enumeración que se le proporcionará al buscador para esta
propiedad.
*** Relación simple con otra entidad (Pet, Vet, ...): No aplica. El
filtro ya viene definido por la entidad que se le proporcionará al
buscador para esta propiedad.
*** Relaciones múltiples (Set, ...): No aplica. El filtro ya viene
definido por la lista de valores que se le proporcionará al buscador
para esta propiedad.
** Operator: And o Or. Es el operador que se utilizará para relacionar
el filtro sobre una propiedad y el siguiente.

Algunos ejemplos serían: findOwnersByFirstNameLike,
findPetsByWeightGreaterThan, findVetsByBirthDayBetween,
findPetsBySendRemindersNot, findPetsByType, findVisitsByPet,
findOwnersByPets, findOwnersByTelephoneIsNotNullAndBirthDayEquals,
findPetsByWeightLessThanEqualsOrTypeOrSendRemindersNot.

Al ejecutar el comando _finder add_ con el nombre del buscador deseado
se generará el buscador en la capa de las entidades, pero no se generará
todavía ningún código en la capa de la vista.

-----------------------------------------------------------------------------------
roo>
        Updated SRC_MAIN_JAVA/com/springsource/petclinic/domain/Owner.java
        Created SRC_MAIN_JAVA/com/springsource/petclinic/domain/Owner_Roo_Finder.aj

-----------------------------------------------------------------------------------

Consultar la documentación del comando
http://docs.spring.io/spring-roo/docs/2.0.0.BUILD-SNAPSHOT/reference/html/#finder-add[finder
add] para más información.

Código generado
---------------

La ejecución del comando _finder add_ desencadenará la modificación de
una anotación en la clase Java de la entidad especificada.

---------------------------------------------------
...
        @RooJpaActiveRecord()
        public class Owner extends AbstractPerson {
        }

---------------------------------------------------

La aparición del atributo _finders_ en la anotación _RooJpaActiveRecord_
de la entidad provocará la generación del aspecto Java correspondiente
que implementará el buscador solicitado.

--------------------------------------------------------------------------------------------------
privileged aspect Owner_Roo_Finder {

         public static TypedQuery<Owner> Owner.findOwnersByLastNameLikeAndCityLike(
                String lastName, String city) {
             if (lastName == null || lastName.length() == 0)
                    throw new IllegalArgumentException("The lastName argument is required");
             lastName = lastName.replace('*', '%');
             if (lastName.charAt(0) != '%') {
                 lastName = "%" + lastName;
             }
             if (lastName.charAt(lastName.length() - 1) != '%') {
                 lastName = lastName + "%";
             }
             if (city == null || city.length() == 0) throw new IllegalArgumentException(
                    "The city argument is required");
             city = city.replace('*', '%');
             if (city.charAt(0) != '%') {
                 city = "%" + city;
             }
             if (city.charAt(city.length() - 1) != '%') {
                 city = city + "%";
             }
             EntityManager em = Owner.entityManager();
             TypedQuery<Owner> q = em.createQuery("SELECT o FROM Owner AS o WHERE " +
                    "LOWER(o.lastName) LIKE LOWER(:lastName) AND LOWER(o.city) LIKE LOWER(:city)",
                    Owner.class);
             q.setParameter("lastName", lastName);
             q.setParameter("city", city);
             return q;
         }
        }
--------------------------------------------------------------------------------------------------

//Return level title
:leveloffset: 0
