Instalación de gvNIX
--------------------

// Push titles down one level.
:leveloffset: 2

Requisitos previos
------------------

Como se comenta en los puntos anteriores gvNIX es un Roo Add-On Suite, 
es decir, un conjunto de Add-Ons que pueden ser instalados sobre una
distribución de Spring Roo.

Por ello, es requisito indispensable disponer de la última versión de
Spring Roo para poder utilizar gvNIX. 

Puedes descargar la última versión de Spring Roo desde 
http://projects.spring.io/spring-roo/#running-from-shell[aquí].

[NOTE]
====
Solo es posible utilizar gvNIX 2.0+ sobre las versiones 2.0
de Spring Roo en adelante. Esto es debido a que la instalación de 
"Roo Add-On Suites" es una característica de las últimas versiones 
de Spring Roo.
====

Para poder ejecutar Spring Roo en nuestro sistema, es necesario tener una
máquina virtual Java instalada.

La lista de requisitos es la siguiente:

* Versión más actual de Java JDK 6 instalado en el sistema. Se 
recomienda utiliar *Java 7*, aunque se dispone de soporte para Java 8.
(http://www.oracle.com/technetwork/java/javase/downloads/index.html[Más
información]).
* Maven 3.0.5 o superior (http://maven.apache.org/).
* Conexión a Internet para poder instalar de forma correcta gvNIX en
la distribución de Spring Roo y descargar las dependencias de los
proyectos generados.

Configuración del entorno
~~~~~~~~~~~~~~~~~~~~~~~~~

La configuración del entorno solo será necesario si se va a utilizar
gvNIX desde la consola del sistema. Por lo tanto, no será necesario
realizar todos los pasos indicados en este punto si se va a utilizar
gvNIX desde Eclipse o STS tal y como se detallará posteriomente.

Una vez descargado el archivo de instalación de Java JDK y Maven veamos
como configurar el entorno de trabajo para usar estas herramientas.

[NOTE]
====
Las siguientes notas sobre configuración son una recomendación de buenas
prácticas. La variable _$HOME_ hace referencia al path del directorio de
raíz de usuario (por ejemplo: _/home/usuario_). Se supondrá instalado
Java JDK y Maven en:

1.  Java JDK 1.6 instalada en: _/home/usuario/software/jdk1.6.0_35_
2.  Maven 3 instalado en: _/home/usuario/software/apache-maven-3.0.5_
====

* *Variables de entorno*
+
En entornos Unix, se puede utilizar _$HOME/.bashrc_ para definir las
variables de entorno y automáticamente se cargarán al abrir una nueva
consola. Es una buena práctica definirlas en nuestro propio archivo y
cargarlo desde el _$HOME/.bashrc_, en este caso dicho archivo se llamará
_$HOME/.bash_devel_.
+
En sistemas Windows, establecer en las propiedades de "Mi PC" únicamente
las variables de entorno que se definen a continuación en el segundo
punto.

** *Modificar _$HOME/.bashrc_ para que cargue el archivo
_$HOME/.bash_devel_*:
+
Añadir al final del archivo .bashrc las siguientes líneas:
+
-----------------------------
# Development settings
if [ -f ~/.bash_devel ]; then
   . ~/.bash_devel
fi
-----------------------------
** *Crear/Modificar _$HOME/.bash_devel_ para añadir las variables de
entorno*:
+
-------------------------------------------------
export JAVA_HOME=$HOME/software/jdk1.6.0_35

export M2_HOME=$HOME/software/apache-maven-3.0.4

export M2=$M2_HOME/bin

export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=512"

export PATH=$JAVA_HOME/bin:$M2:$PATH
-------------------------------------------------
+
Con estos cambios cada vez que se abra una consola del sistema estarán
cargadas las variables de entorno. También se puede cargar los cambios
realizados en estos ficheros ejecutando el comando _source_ en la
consola de entornos Unix:
+
----------------------
bash:~$ source .bashrc
----------------------
+
Una vez realizados estos cambios se puede comprobar su funcionamiento:
(Ejecutando los comandos siguientes veremos salidas similares a las que
se muestran)
+
----------------------------------------------------------------------------
bash:~$
java version "1.6.0_35"
Java(TM) SE Runtime Environment (build 1.6.0_35-b04)
Java HotSpot(TM) 64-Bit Server VM (build 20.8-b03, mixed mode)
bash:~$
Apache Maven 3.0.5 (r1056850; 2012-01-09 17:58:10+0100)
Java version: 1.6.0_35, vendor: Sun Microsystems Inc.
Java home: /home/usuario/software/jdk1.6.0_35/jre
Default locale: es_ES, platform encoding: UTF-8
OS name: "linux", version: "3.2.0-30-generic", arch: "amd64", family: "unix"
----------------------------------------------------------------------------

Acceso a través de un proxy
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Si la conexión a Internet se realiza a través de un proxy, habrá que
configurar tanto Java como Maven para que puedan acceder al exterior
correctamente.

* *Java a través de proxy*:
+
Es posible que la red en la que se esté trabajando requiera de la
configuración de un Proxy para el acesso a internet.
+
gvNIX/Roo dispone de un comando que indica si la instalación de Java
está, o no, configurada para conectar a Internet a través de un proxy.
+
------------------------------------------------------------------------------------
roo>
                     *** Your system has no proxy setup ***
http://download.oracle.com/javase/6/docs/technotes/guides/net/proxies.html offers
useful information.
For most people, simply edit /etc/java-6-openjdk/net.properties (or equivalent) and
set the java.net.useSystemProxies=true property to use your operating system-defined
proxy settings.
------------------------------------------------------------------------------------
+
En el ejemplo anterior indica que no hay ningún proxy configurado. Si es
necesario hacerlo se debe seguir la guía tal y como indica la salida del
comando.
+
Si se han seguido las recomendaciones para instalar Java, ir a
/home/usuario/software/jdk1.6.0_35/jre/lib. Aquí estará el archivo
net.properties que se debe editar y configurarlo según las necesidades.
+
La opción más sencilla es establecer la propiedad
_java.net.useSystemProxies=true_. Esto le indica a Java que debe
utilizar la configuración del proxy que previamente se haya definido en
el sistema operativo. Sin embargo puede no funcionar en todos los
sistemas.
+
En caso de no funcionar lo anterior, definir la configuración específica
del proxy buscando las propiedades descritas a continuación y
añadiéndolas si no existen:
+
------------------------------------------------------------
java.net.useSystemProxies=false

http.proxyHost=host.proxy.de.red (ejemplo: proxy.mired.com)
http.proxyPort=puerto (ejemplo: 8080)
http.nonProxyHosts=hosts.a.ignorar.1|host.a.ignorar.2
 (ejemplo: localhost|127.0.0.1|192.168.1.*|*.mired.com)

https.proxyHost=host.proxy.de.red (ejemplo: proxy.mired.com)
https.proxyPort=puerto (ejemplo: 8080)
https.nonProxyHosts=hosts.a.ignorar.1|host.a.ignorar.2
 (ejemplo: localhost|127.0.0.1|192.168.1.*|*.mired.com)
------------------------------------------------------------
+
Si se configura alguna de estas propiedades el comando _proxy
configuration_ informará de los valores configurados.
* *Maven a través de proxy:*
+
Algunos comandos de gvNIX/Roo utilizan la herramienta Maven y dicha
herramienta en algunos casos necesita conexión con Internet para, por
ejemplo, descargar las dependencias de los proyectos generados.
+
Es por ello que si se accede a Internet a través de un proxy se deberá
configurar en el fichero $M2_HOME/conf/settings.xml las siguientes
secciones en el lugar adecuado del fichero. Revisar las secciones
comentadas porque existirá ya una sección de este tipo como ejemplo:
+
-----------------------------------------------------------------
<proxy>
        <id>Proxyhttp</id>
        <active>true</active>
        <protocol>http</protocol>
        <host>host.proxy.de.red (ejemplo: proxy.mired.com)</host>
        <port>puerto (ejemplo: 8080)</port>
</proxy>
<proxy>
        <id>Proxyhttps</id>
        <active>true</active>
        <protocol>https</protocol>
        <host>host.proxy.de.red (ejemplo: proxy.mired.com)</host>
        <port>puerto (ejemplo: 8080)</port>
</proxy>
-----------------------------------------------------------------

Instalación
-----------

Para instalar el Roo Add-On Suite gvNIX es necesario que nuestra distribución de Roo
sepa donde están alojados todos los componentes que la forman. Por ello, es necesario
instalar en nuestra distribución el repositorio donde se encuentran dichos componentes.

Sigue los siguientes pasos para instalar el repositorio de gvNIX en tu distribución de
Spring Roo 2.0+:

1. Ejecuta la consola de Spring Roo 2.0+:
+
--------------------------------------------
bash:~$ cd /tmp/new_project
bash:~$ ~/software/spring-roo-2.0/bin/roo.sh
--------------------------------------------

2. Accede al http://projects.spring.io/spring-roo/marketplace/["Roo Market Place"] y
copia la URL del repositorio de gvNIX (http://repository.gvnix.org/index.xml).

3. Ejecuta el siguiente comando en tu consola de Spring Roo 2.0+ para 
instalar el repositorio anterior:
+
----------------------------------------------------------------------
roo> addon repository add --url http://repository.gvnix.org/index.xml
----------------------------------------------------------------------

4. Valida que se ha instalado el repositorio de forma correcta listando los componentes
que están disponibles en dicho repositorio. Para ello, ejecuta el siguiente comando:
+
---------------------------------
roo> addon repository introspect
---------------------------------

5. Si todo ha salido bien, aparecerá un listado mostrando todos los componente que forman
parte de la distribución gvNIX.
+
----------------------------------------------------------------------------------------
Not Installed        gvNIX - Addon - Bootstrap3 support (2.0.0.M1)
Not Installed        gvNIX - Addon - Co-official languages of Spain (2.0.0.M1)
Not Installed        gvNIX - Addon - Dynamic Configuration (2.0.0.M1)
Not Installed        gvNIX - Addon - GEO Support (2.0.0.M1)
Not Installed        gvNIX - Addon - JPA layer services (2.0.0.M1)
Not Installed        gvNIX - Addon - Loupe Fields (2.0.0.M1)
Not Installed        gvNIX - Addon - Monitoring Support (2.0.0.M1)
Not Installed        gvNIX - Addon - Optimistic Concurrency Control (2.0.0.M1)
Not Installed        gvNIX - Addon - Services Management (2.0.0.M1)
Not Installed        gvNIX - Addon - Typical Security (2.0.0.M1)
Not Installed        gvNIX - Addon - Web Datatables Addon (2.0.0.M1)
Not Installed        gvNIX - Addon - Web MVC (JSP) layer services (2.0.0.M1)
Not Installed        gvNIX - Addon - Web MVC Bindings (2.0.0.M1)
Not Installed        gvNIX - Addon - Web MVC Dialogs (2.0.0.M1)
Not Installed        gvNIX - Addon - Web MVC Menu (2.0.0.M1)
Not Installed        gvNIX - Addon - Web Report (2.0.0.M1)
Not Installed        gvNIX - Annotations - GEO Support (2.0.0.M1)
Not Installed        gvNIX - Annotations - JPA layer services (2.0.0.M1)
Not Installed        gvNIX - Annotations - Loupe Fields (2.0.0.M1)
Not Installed        gvNIX - Annotations - Optimistic Concurrency Control (2.0.0.M1)
Not Installed        gvNIX - Annotations - Services Management (2.0.0.M1)
Not Installed        gvNIX - Annotations - Web Datatables Addon (2.0.0.M1)
Not Installed        gvNIX - Annotations - Web MVC (JSP) layer services (2.0.0.M1)
Not Installed        gvNIX - Annotations - Web MVC Bindings (2.0.0.M1)
Not Installed        gvNIX - Annotations - Web MVC Dialogs (2.0.0.M1)
Not Installed        gvNIX - Annotations - Web Report (2.0.0.M1)
Not Installed        gvNIX - Roo Addon Suite (2.0.0.M1)
Not Installed        gvNIX - Support Module (2.0.0.M1)
Not Installed        Spring Roo - Wrapping - derby (10.8.2.2_0002)
Not Installed        Spring Roo - Wrapping - derbyclient (10.8.2.2_0002)
Not Installed        Spring Roo - Wrapping - firebird (2.1.6.0021)
Not Installed        Spring Roo - Wrapping - jtds (1.2.4.0011)
Not Installed        Spring Roo - Wrapping - jtopen (6.7.0.0011)
Not Installed        Spring Roo - Wrapping - mysql-connector-java (5.1.18.0002)
Not Installed        Spring Roo - Wrapping - postgresql-jdbc3 (9.1.0.901_0003)

35 available bundles on installed repositories were found
----------------------------------------------------------------------------------------

6. Ahora que ya tienes instalado el repositorio que contiene los componentes de gvNIX, continuamos con
la instalación de los mismos. Para ello ejecuta el siguiente comando:
+
----------------------------------------------------------------------
roo> addon suite install name --symbolicName org.gvnix.roo.addon.suite
----------------------------------------------------------------------

7. Valida que se ha instalado el Roo Add-On Suite de gvNIX ejecutando el siguiente comando:
+
----------------------
roo> addon suite list
----------------------

8. Si todo ha salido bien, aparecerá un listado mostrando todos los Roo Add-On Suites que tienes
instalados en tu distribución de Spring Roo:
+
----------------------------------------------------------------
Getting all 'Roo Addon Suites' installed on Spring Roo Shell... 

   org.osgi.service.subsystem.root
   org.gvnix.roo.addon.suite
   
1 Roo Addon Suites were found at your Spring Roo installation
----------------------------------------------------------------

9. Para finalizar, valida que todos los componentes de gvNIX se han instalado correctamente 
en la distribución de Sprign Roo ejecutando el siguiente comando:
+
----------------
roo> addon list
----------------

10. Si todo ha salido bien, al final del listado que aparecerá en la consola, podrás ver
todos los componentes de gvNIX instalados y activados del siguiente modo:
+
------------------------------------------------------------------------------------------
   86|Active     |    1|gvNIX - Annotations - GEO Support (2.0.0.M1)
   87|Active     |    1|gvNIX - Addon - Dynamic Configuration (2.0.0.M1)
   88|Active     |    1|gvNIX - Addon - Loupe Fields (2.0.0.M1)
   89|Active     |    1|gvNIX - Addon - Web MVC (JSP) layer services (2.0.0.M1)
   90|Active     |    1|gvNIX - Annotations - Web Datatables Addon (2.0.0.M1)
   91|Active     |    1|gvNIX - Addon - JPA layer services (2.0.0.M1)
   92|Active     |    1|gvNIX - Addon - Web Datatables Addon (2.0.0.M1)
   93|Active     |    1|gvNIX - Annotations - Web MVC (JSP) layer services (2.0.0.M1)
   94|Active     |    1|gvNIX - Addon - Services Management (2.0.0.M1)
   95|Active     |    1|gvNIX - Annotations - Web Report (2.0.0.M1)
   96|Active     |    1|gvNIX - Addon - Co-official languages of Spain (2.0.0.M1)
   97|Active     |    1|gvNIX - Annotations - Optimistic Concurrency Control (2.0.0.M1)
   98|Active     |    1|gvNIX - Addon - Web MVC Dialogs (2.0.0.M1)
   99|Active     |    1|gvNIX - Annotations - Services Management (2.0.0.M1)
  100|Active     |    1|gvNIX - Addon - Monitoring Support (2.0.0.M1)
  101|Active     |    1|gvNIX - Addon - Bootstrap3 support (2.0.0.M1)
  102|Active     |    1|gvNIX - Annotations - Web MVC Dialogs (2.0.0.M1)
  103|Active     |    1|gvNIX - Addon - GEO Support (2.0.0.M1)
  104|Active     |    1|gvNIX - Addon - Optimistic Concurrency Control (2.0.0.M1)
  105|Active     |    1|gvNIX - Support Module (2.0.0.M1)
  106|Active     |    1|gvNIX - Annotations - Loupe Fields (2.0.0.M1)
  107|Active     |    1|gvNIX - Annotations - JPA layer services (2.0.0.M1)
  108|Active     |    1|gvNIX - Addon - Web Report (2.0.0.M1)
  109|Active     |    1|gvNIX - Annotations - Web MVC Bindings (2.0.0.M1)
  110|Active     |    1|gvNIX - Addon - Typical Security (2.0.0.M1)
  111|Active     |    1|gvNIX - Addon - Web MVC Menu (2.0.0.M1)
  112|Active     |    1|gvNIX - Addon - Web MVC Bindings (2.0.0.M1)
------------------------------------------------------------------------------------------

Una vez hecho esto, ya se puede trabajar con el entorno gvNIX desde la
línea de comandos. Sin embargo, se recomienda utilizar un IDE de
desarrollo que permita integrar el entorno gvNIX como, por ejemplo STS o
Eclipse tal y como se verá en la sección posterior. Aún así, si se desea
abrir el intérprete de comandos desde la línea de comandos se puede
hacer de la siguiente forma:

* Cambiar al directorio donde se encuentre el proyecto Java existente o
a un directorio vacío en el caso de tratarse de un proyecto nuevo:
+
------------------------------
bash:~$ cd ~/project-directory
------------------------------
* Ejecutar el intérprete de comando de Roo para interactuar con el
proyecto Java:
+
-----------------------------------------------------------
bash:~/project-directory$ roo.sh

(En sistemas windows el intérprete se abrirá con roo.bat)
-----------------------------------------------------------
* Con esto se abrirá la consola de Roo y se mostrará algo similar a lo
siguiente:
+
------------------------------------------------------------------------------------------
                ____  ____  ____
               / __ \/ __ \/ __ \
              / /_/ / / / / / / /
             / _, _/ /_/ / /_/ /   
            /_/ |_|\____/\____/    x.x.x-RELEASE [rev xxxxxxx]


            Welcome to Spring Roo. For assistance press TAB or type "hint" then hit ENTER.
            roo>

------------------------------------------------------------------------------------------

// Return to normal title levels.
:leveloffset: 0