//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//
//   $ asciidoc -b html5 td-addon-web-report.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 td-addon-web-report.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf td-addon-web-report.adoc


= gvNIX Web report add-on
:Project:   gvNIX, un Addon de Spring Roo Suite
:Copyright: 2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y Administración Pública - CC BY-NC-SA 3.0
:Author:    Dirección General de Tecnologías de la Información, Asociación gvSIG, DISID Corporation, S.L.
:corpsite: www.gvnix.org
:doctype: article
:keywords: gvNIX, Documentation
//:date: $Date: 2011-06-30 15:40:23 +0200 (jue, 30 jun 2011) $
:toc:
:toc-placement: left
:toc-title: Table of Contents
:toclevels: 4
:numbered:
:sectnumlevels: 4
:source-highlighter:  pygments
ifdef::backend-pdf[]
:pdf-style: asciidoctor
:pagenums:
:pygments-style:  bw
endif::[]


_2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y
Administración Pública - Generalitat Valenciana._
This work is licensed under the http://creativecommons.org/licenses/by-sa/3.0/[Creative Commons Attribution-Share Alike
3.0 Unported License]. If you remix, transform, or build upon the material, you  must give appropriate credit and
distribute your contributions under the same license as the original.

[[introduction]]
Introduction
------------

This document contents relative to this add-on.

[[requirements]]
Requirements
------------

In the first release of this add-on, it have to install JasperReports
support and create a sample report of Roo projects.

The desired features of the add-on could be:

* setup of several Java Report tools.
* create reports of the set Java Report tool for all the finder methods
of the project Entities.
* create a report for a desired finder method of an Entity.
* remove a report.
* list all the reports in the project.

[[analysis]]
Analysis
--------

(First version)

* gvNIX command:
+
[source, sh]
----
web report add --controller <controller> --reportName <report_name> --format <format>
----

When the command is issued the following operations must be performed:

* Add Maven dependencies for JasperReports to the pom.xml of the
project.

* Set configuration for the JasperReport `views` in:
** _WEB-INF/spring/webmvc-config.xml_
** _WEB-INF/spring/jasper-views.xml_ (this one will be created the first
time)

* Annotate the <controller> with the annotation _@GvNixReports({"<report_name>|<format>"})_.
Add to the <controller>Controler.aj a new controller method with the
 _@RequestMapping("/reports/<report_name>")_ annotation and accepting a request
 paramater _format_ (String). In this controller the report DataSource will be
 populated with the result of the _<entity>.findEntries(0, 10)_.
 The entity will be given by the fromBackingOject attribute in the RooWebScaffold annotation.

*  Add a new file under WEB-INF/reports with the name <report_name>.jrxml.
This report will be the sample report showing <report_name> in the title of the
  report and some fields of the entity in the detail band, so, the _<field/>_
  and _<textField/>_ nodes must be created in the jrxml file.

* Create a new JSPX under the <entity> views folder with <report_name> as file
name. The new JSP will have a simple form with a drop-down select field with
formats defined for this report and a submit button requesting the report
generation. Add a new menu entry under the <entity> section pointing to the
 new controller action.

Of course, the command must check if it was issued before, so the
configuration of JasperReports dependencies and "views" must be
skipped.

We decided annotate the Controller instead of the Entity because the
access to the report generation depends directly of the web tier. The
Controller informs, through the fromBackingObject attribute in the
@RooWebScaffold, the related Entity.

[[addon-annotations]]
Addon Annotations
-----------------

* _@GvNixReports_: Defines the list of supported reports handled by the
annotated Controller.

[[add-a-new-report]]
Add a new report
~~~~~~~~~~~~~~~~

Define _@GvNIXReports_ setting _reportName|format_ as value. The
annotation support as many _reportName|format_ pairs as reports you must
handle with the annotated Controller.

The format part of the annotation value can be a String with the formats
you want available for this report. Supported formats are: _pdf, xls,
csv, html_. So, the annotation will have the following look
_@GvNIXReports({"<reportName>|<formats as csv>"[,"<reportName>|<formats as csv>"]})_.
Once a report has been defined you can add or remove supported formats.

[[operations]]
Operations
----------

[[setup]]
setup
~~~~~

Performs the needed operations for give JasperReports support in the
project.

* Add a repository definition, some properties, add-on library
dependency and JasperReports dependencies to porm.xml.
* Modify Spring MVC config file (_webmvc-config.xml_) adding
JasperReportsXmlViewResolver as views resolver.
* Install the JasperReports views config file *jasper-views.xml*.
* Install JasperReports fonts. With them it install a file defining a
JasperReport extension where the fonts are set for the report render.

[[annotatetype]]
annotateType
~~~~~~~~~~~~

Add the _GvNIXReports_ annotation to the Controller class or update its
value.

Annotate Controller triggers all the Metadata operations ending with a
fully functional report in the project. These operations are:

* If _setup_ operation has not yet been performed, _annotateType_
launches it.
* Creates and installs the sample report design file.
* Adds a JasperReport view definition in _jasper-views.xml_.
* Creates / Updates the Controller ITD with the methods handling report
requests.
* Installs a JSP with the form for report requests.

[[metadata]]
Metadata
--------

[[reportmetadaprovider]]
ReportMetadaProvider
~~~~~~~~~~~~~~~~~~~~

Records dependencies between WebScaffoldMetadata and ReportMetada so,
any change in _@GvNIXReports_ values triggers operations over
ReportMetadata.

Also it provides components and data needed by RepotMetadata.

[[reportmetada]]
ReportMetada
~~~~~~~~~~~~

Represents the reports installed in a Controller. It’s responsible of
ITD creation. Here we create the methods of the Controller handling
requests related with reports, that is, a method returning the form to
request the report and the method returning the generated report. Other
important operation performed by ReportMetadata is the creation of the
sample report design file, a JRXML file as a starting point of the
report development.

[[interesting-member-fields]]
Interesting member fields
^^^^^^^^^^^^^^^^^^^^^^^^^

* _reportMethods_: A list of _MethodMetada_ with the metadata of methods
in Report ITD.
* _controllerMethods_: A list of _MethodMetada_ with metadata of all the
methods in the WebScaffold. This is needed in in order to check if
methods that ReportMetadata created in the ITD already exist in
WebScaffold.
* _installedReports_: A list of Strings representing the values in
_@GvNIXReports_.
* _webScaffoldMetada_: Metadata about the Controller. We need it for
some operations done in _ReportJspMetadataListener_.


[[reportjspmetadata]]
ReportJspMetadata
~~~~~~~~~~~~~~~~~

Represents the JSP of the form in the web tier that allow users to
request a report.

Just stores a reference to its ReportMetadata.

[[reportjspmetadatalistener]]
ReportJspMetadataListener
~~~~~~~~~~~~~~~~~~~~~~~~~

Handles the changes in the ReportMetadata ITD, so when they happen, it
triggers changes in the JSP. Actually, just the creation of the JSP. In
the future other changes as adapt the form to the fields finder form
will be performed.

So, its main purpose is to create the JSP with the form requesting the
report.

[[proof-of-concept]]
Proof of Concept
----------------

* http://scmcit.gva.es/svn/gvnix-proof/trunk/petclinic-report
* http://scmcit.gva.es/svn/gvnix-proof/trunk/jasperreports-app
* https://svn.disid.com/svn/disid/proof/gvnix/jasperreports-app

[[todo]]
TODO
----

* https://jira.springsource.org/browse/ROO-228?focusedCommentId=64509&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#action_64509
* Revisit ReportMetadataProvider in order to modify the method used to
retrieve WebScaffoldMetadata via MetadataService instead of
WebScaffoldMetadataProvider.
