gvNIX Web report add-on
=======================
:author: DISID Corporation, S.L.
:date: $Date$

This work is licensed under the Creative Commons Attribution-Share Alike
3.0 Unported License. To view a copy of this license, visit
http://creativecommons.org/licenses/by-sa/3.0/ or send a letter to
Creative Commons, 171 Second Street, Suite 300, San Francisco,
California, 94105, USA.

[[introduction]]
Introduction
------------

Adds JasperReports support to Roo-based project.

[[requirements]]
Requirements
~~~~~~~~~~~~

* JDK 1.6+
* Maven 2+
* gvNIX - Spring Roo - Addon - Web Report
* Eclipse Helios 3.6.0 (optional)

[[install-addon-services-management]]
Install Addon Services Management
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Options:

* To install gvNIX 0.6.0 that contains the add-on installed.
* OR, to install in Spring Roo 1.1.2
** Trust on PGP KEY ID used to sign the add-on. Note that gvNIX project
members have their PGP KEYs IDs published at
https://code.google.com/p/gvnix/people/list:
+
----------------------------
pgp trust --keyId 0xC5FC814B
----------------------------
** Run the command below:
+
------------------------------------------------------------------------
addon install bundle --bundleSymbolicName org.gvnix.web.report.roo.addon
------------------------------------------------------------------------

[[use-case-reports-support-in-pet-clinic]]
Use case: Reports support in Pet clinic
---------------------------------------

Create a new directory for the project:

--------------
Bash shell:

  mkdir clinic
  cd clinic
--------------

Start gvNIX:

------------------------------------------------------------------------------
clinic$ gvnix.sh
    ____  ____  ____  
   / __ \/ __ \/ __ \ 
  / /_/ / / / / / / / 
 / _, _/ /_/ / /_/ /   1.1.2.RELEASE [rev fbc33bb]
/_/ |_|\____/\____/   gvNIX distribution 0.6.0


Welcome to Spring Roo. For assistance press TAB or type "hint" then hit ENTER.
roo>
------------------------------------------------------------------------------

Create the project:

----------------------
roo> script clinic.roo
----------------------

Add a new report:

--------------------------------------------------------------------------------------------
roo> web report add --controller ~.web.PetController --reportName PetReport --format pdf,xls
--------------------------------------------------------------------------------------------

Run mvn tomcat:run in the root of your project and the report should be
available under the URL
http://localhost:8080/petclinic/pets/reports/petreport?form

[[about-the-command]]
About the command
~~~~~~~~~~~~~~~~~

The command performs the following operations:

* Adds the add-on and JasperReports dependencies to the project
_pom.xml_
* Adds JasperReporViewsResolver in _webmv-config.xml_
* Installs _jasper-views.xml_ as config file for
`CustomJasperReportsMultiFormatView.java`.
* Installs _jasperreports_extension.properties_ and the FreeSans font
family TTF fonts in the webapp classpath.

The command accepts the parameters below:

* _controller_: Is an existing class in your project handling web
requests. This controller must be annotated with
* *@RooWebScaffold* and its attribute _formBackingObject_ must be
informed. The add-on takes this annotation and its attribute value for
code generation. The value of _formBackingObject_ informs which is the
Entity exposed by the controller. The parameter is mandatory and has not
default value.
* _reportName_: Is the name of the report. The value of the parameter
will be transformed to lower case. The parameter is mandatory and has
not default value.
* _format_: The value can be a single format (pdf (Portable Document
Format) | xls (Excel) | csv (Comma Separated Values) | html (HyperText
Markup Language)) or a comma separated value string given several
formats (ie: pdf,xls) at once. This parameter is optional and its
default value is _pdf_.

Command unleashed:

When the command is launched installs a Java file class into
_controller-sub-package.servlet.view.jasperreports sub-package_ that
handles the render report operation and makes possible a better naming
of the generated output file. Its name is
`CustomJasperReportsMultiFormatView.java`. This class is installed only
once, the following invocations checks it the Java file exists.

Over this class a new bean is defined in *jasper-views.xml* file. This
new bean will have _<formBackingObject_name>_<reportname>_ as id and the
class will be our CustomJasperReportsMultiFormatView. The bean defines a
JasperReport view resolver.

The command creates a sample report in JasperReport XML format (jrxml)
using three fields of the entity informed by _formBackingObject_
attribute in annotation @RooWebScaffold as detail of the report. The
sample report is in the file
_src/main/webapp/WEB-INF/reports/<formBackingObject_name>_<reportname>.jrxml_.
As the report renders the title in bold, it needs to have available a
bold TTF font. So, it installs some fonts under
_src/main/webapp/WEB-INF/classes/jasperfonts/_.

In order to handle the report requests a new view is installed under
_src/main/webapp/WEB-INF/views/<fromBakingObject_name>/<reportname>.jspx_.
This view is a simple form where the user can select the output format
of the report and request it using the submit button. This form needs an
end-point listening its requests, so, the command creates two methods in
an ITD file called `<controller>_Roo_GvNIXReport.aj`. One is the method
returning the form view (`generate<Reportname>Form(...)`) and the other
is the method collecting the data needed for render the report and
returning the output file (`generate<Reportname>(..)`). This method
invokes `<formBackingObject>.find<formBackingObject>Entires(0, 10)` as
example of how to populate the report datasource.

The command can be launched twice with the the same _controller_ and
same _reportName_ values but given other _format_. If so, the new
formats are added as supported format of the existing report. You can
not add the same report with the same formats twice instead.

[[modifying-source-code]]
Modifying source code
^^^^^^^^^^^^^^^^^^^^^

Annotate the Controller with:

------------------------------------------------------------------------
@GvNIXReports({ "<reportName>|<formats>"[, "<reportName2>|<formats>"] })
------------------------------------------------------------------------

save file changes and let gvNIX/Roo do its magic.

The value of the *@GvNIXReports* annotation is case insensitive, so,
something like:

---------------------------------------------------------------
@GvNIXReports({ "myfirstreport|pdf", "myFirstREPORT|xls,csv" })
---------------------------------------------------------------

is equivalent to:

----------------------------------------------
@GvNIXReports({ "myfirstreport|pdf,xls,csv" })
----------------------------------------------
