//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//
//   $ asciidoc -b html5 td-web-i18n.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 td-web-i18n.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf td-web-i18n.adoc


= Addon web i18n
:Project:   gvNIX, un Addon de Spring Roo Suite
:Copyright: 2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y Administración Pública - CC BY-NC-SA 3.0
:Author:    Dirección General de Tecnologías de la Información, Asociación gvSIG, DISID Corporation, S.L.
:corpsite: www.gvnix.org
:doctype: article
:keywords: gvNIX, Documentation
:toc:
:toc-placement: left
:toc-title: Table of Contents
:toclevels: 4
:numbered:
:sectnumlevels: 4
:source-highlighter:  pygments
ifdef::backend-pdf[]
:pdf-style: asciidoctor
:pagenums:
:pygments-style:  bw
endif::[]

_2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y
Administración Pública - Generalitat Valenciana._ Esta obra está bajo la licencia
http://creativecommons.org/licenses/by-sa/3.0/es/[Reconocimiento-Compartir bajo la misma licencia 3.0 España]
de Creative Commons. Puede copiarla, distribuirla y comunicarla públicamente
siempre que especifique sus autores y comparta cualquier obra derivada bajo la
misma licencia.

[[proof-of-concept]]
Proof of Concept
----------------

* http://scmcit.gva.es/svn/gvnix-proof/trunk/petclinic-i18n

[[todo]]
TODO
----

En el ejemplo petclinic, con el tema de la CIT instalado, no me aparece
la bandera del cambio de idioma a Valenciano, sin embargo sí que me
funciona accediendo directamente a la URL
_http://localhost:8080/petclinic/?lang=ca_.

----
* web mvc install language –code ca
* theme install –id cit
* theme set –id cit
----

Se debe a que ejecuto la instalación del idioma antes de instalar y
establecer el tema.

Si después de instalar y establecer el tema vuelvo a ejecutar la
instalación del idioma, aparece la bandera correctamente. Es por ello
que no lo considero un error, simplemente será dejar claro en la
documentación del add-on que debe su ejecución debe ser posterior al
instalar y establecer un nuevo tema.

Es un problema del tema. Roo pone los enlaces para el cambio de idioma
en footer.jspx, el problema está en que los temas tb pueden incluir este
fichero y sobreescriben el que ha modificado Roo.

La solución pasa por leer los idiomas instalados en el footer.jspx antes
de sobreescribir, una vez sobreescrito actualizar el footer.jsp del tema
con los idiomas leídos.
