//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//   $ asciidoc -b html5 td-addon-web-mvc-bootstrap_es.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 td-addon-web-mvc-bootstrap_es.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf td-addon-web-mvc-bootstrap_es.adoc
//
= {title}
:title:			gvNIX 1.3.1 - Análisis y Concepto HTML5 y CSS3 Bootstrap
:author: 		DISID Corporation S.L. - Pivotal Software, Inc
:authorsite: 		www.disid.com
:copyright: 		CC BY-NC-SA 3.0
:doctype: 		article
:toc:
:toc-placement:		left
:toc-title:		Índice
:toclevels: 		4
:numbered:
:sectnumlevels:		4
ifdef::backend-pdf[]
:pdf-style:		asciidoctor
:pagenums:
//:pygments-style: 	bw
//:source-highlighter: 	pygments
endif::[]

[[descripcion-doc]]
== Descripción del documento

Documento de análisis y diseño técnico de una nueva funcionalidad de gvNIX que permita modificar la capa de la vista de las aplicaciones generadas para generar páginas HTML5 y CSS3 además de ser páginas adaptativas (en inglés _responsive UI_) utilizando Bootstrap.

[[diseño]]
== Diseño técnico

Esta nueva funcionalidad se implementará en un nuevo add-on llamado *addon-web-mvc-bootstrap*.

En los siguientes apartados se desarrolla el diseño técnico de este add-on en lo que se refiere al soporte para la capa de la vista de las aplicaciones generadas utilizando páginas HTML5 y CSS3 Bootstrap.

[[analisis-solucion]]
=== Análisis de la solución

El soporte para integrar páginas HTML5 y CSS3 en la capa de la vista consiste en que las aplicaciones desarrolladas utilizando la herramienta de desarrollo gvNIX, sean capaces de:

- Adaptar su contenido a todas las resoluciones de pantalla disponibles en los diferentes dispositivos.

Para añadir este soporte, será necesario aplicar los siguientes cambios en la estructura del proyecto generado:

* Incluir *nuevos ficheros* javascript, tags, estilos, imágenes, librerías Bootstrap, etc.. en el proyecto generado.
* Añadir estos nuevos ficheros y componentes al *cargar* la capa de la vista para que estén disponibles.
* *Modificar estructura* de componentes de la capa de la vista (tags, jspx, layouts, etc..) para que sigan la estructura de Bootstrap. 

[[analisis-funcional]]
=== Análisis funcional

Implementar la solución indicada en el punto anterior requiere desarrollar los siguientes comandos gvNIX:

- *web mvc bootstrap setup*: Se encargará de incluir todos los ficheros necesarios para que la aplicación generada utilice páginas HTML5 y CSS3. Actualizará la estructura de los ficheros existentes de la capa de la vista a estructura Bootstrap e incluirá los componentes anteriores al fichero de carga de estilos y scripts.

- *web mvc bootstrap update*: Una vez aplicado Bootstrap, se pueden instalar componentes que no sigan la estructura Bootstrap por defecto. Este comando se encargará de actualizar estos nuevos componentes añadidos para que cumplan la estructura de Bootstrap.

[[diseño-tecnico]]
=== Diseño técnico
 
[[requisitos]]
==== Requisitos

1. Para que los componentes y comandos del soporte *HTML y CSS3 con Bootstrap* estén disponibles, es necesario se haya integrado el componente jQuery en el proyecto generado. Para ello es necesario haber ejecutado el comando *web mvc jquery setup.*

[[web-mvc-bootstrap-setup]]
==== web mvc bootstrap setup

Para una mejor comprensión del comando, nos apoyaremos en el siguiente ejemplo para explicar qué acciones realizará en la aplicación:

	web mvc bootstrap setup

Aplicará los siguientes cambios:

1. Se añaden los ficheros *javascript*, estilos *CSS*, librerías *Bootstrap*, *imágenes*, *fuentes*, etc... necesarios para el correcto funcionamiento del soporte adaptativo. 
2. Actualizará el fichero existente *standard.css* para que aplique los nuevos estilos.
3. Modificará las *clases y estructura HTML de los tagx* existentes en el proyecto para que utilicen la estructura Bootstrap. 
4. Actualizará los *layouts* para seguir la estructura HTML de Bootstrap.
5. Actualizará las *vistas JSP comunes* (index.jspx, footer.jspx, header.jspx, etc..) para que utilicen la estructura Bootstrap.
6. Actualizará *TODAS las vistas jsp* de la aplicación para que utilicen los tags de *JQuery* (create, update, show, list, finders).
7. Comprobará si está instalado el *addon de datatables*. Si está instalado genera los recursos necesarios para que los componentes Datatables utilicen estructura Bootstrap. Si no está instalado el addon Datatables, ignora esta instalación.
8. Comprobará si está instalada la seguridad (*security setup*). Si está instalado modifica el fichero login.jspx para que cumpla con la estructura Bootstrap.

[[web-mvc-bootstrap-update]]
==== web mvc bootstrap update
	
Este comando solo estará disponible una vez ejecutado el comando de instalación de Bootstrap. (web mvc bootstrap setup).

Solo será necesario ejecutar este comando en caso de instalar un nuevo componente que no cumpla con la estructura de Bootstrap. Para esta versión, solo será necesario ejecutarlo si se instala el componente Datatables o se aplica seguridad al proyecto.

Para una mejor comprensión del comando, nos apoyaremos en el siguiente ejemplo para explicar qué acciones realizará en la aplicación:

	web mvc bootstrap update

Aplicará los siguientes cambios:

1. Actualizará la estructura de los componentes instalados para que utilicen la estructura de Bootstrap.
2. En caso del componente *Datatables* se incluirán ficheros CSS con los nuevos estilos del componente para apariencia Bootstrap.
3. En caso de añadir una *nueva entidad y aplicar scaffold* para generar la capa web al ejecutar este comando también se actualizarán los jspx para que utilice los tags de *jquery.*
