//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//
//   $ asciidoc -b html5 readme.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 readme.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf readme.adoc


= gvNIX Web Binging add-on
:Project:   gvNIX, un Addon de Spring Roo Suite
:Copyright: 2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y Administración Pública - CC BY-NC-SA 3.0
:Author:    Dirección General de Tecnologías de la Información, Asociación gvSIG, DISID Corporation, S.L.
:corpsite: www.gvnix.org
:doctype: article
:keywords: gvNIX, Documentation
:toc:
:toc-placement: left
:toc-title: Table of Contents
:toclevels: 4
:numbered:
:sectnumlevels: 4
:source-highlighter:  pygments
ifdef::backend-pdf[]
:pdf-style: asciidoctor
:pagenums:
:pygments-style:  bw
endif::[]


_2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y
Administración Pública - Generalitat Valenciana._
This work is licensed under the http://creativecommons.org/licenses/by-sa/3.0/[Creative Commons Attribution-Share Alike
3.0 Unported License]. If you remix, transform, or build upon the material, you  must give appropriate credit and
distribute your contributions under the same license as the original.

[[introduction]]
Introduction
------------

Add-on giving support for Spring MVC editors configuration.

[[project-contents]]
Project contents
----------------

This folder contains add-on sources and documents folder `docs` with
documentation of this project.

[[installation-proof]]
Installation Proof
------------------

[[install-the-add-on]]
Install the Add-on
~~~~~~~~~~~~~~~~~~

Install the Add-on in gvNIX/Roo shell with the required commands for
1.1.5-RELEASE version.

[[create-a-web-application]]
Create a web application
~~~~~~~~~~~~~~~~~~~~~~~~

Create a web application with gvNIX/Roo Shell script:

[source, sh]
----
script clinic.roo
----

Run the add-on command:

[source, sh]
----
web mvc binding stringTrimmer
----
