================================== gvNIX Web Binging add-on
==================================

:Project: gvNIX. Spring Roo based RAD tool :Copyright: 2010 (C)
Dirección General de Tecnologías de la Información - Conselleria
d’Hisenda i Administració Pública :Author: DISID Corporation, S.L.
:Revision: latexmath:[$Rev: 1177 $] :Date:
latexmath:[$Date: 2011-09-20 11:06:13 +0200 (mar, 20 sep 2011) $]

This work is licensed under the Creative Commons Attribution-Share Alike
3.0 Unported License. To view a copy of this license, visit
http://creativecommons.org/licenses/by-sa/3.0/ or send a letter to
Creative Commons, 171 Second Street, Suite 300, San Francisco,
California, 94105, USA.

.. contents:: :depth: 2 :backlinks: none

.. |date| date::

[[introduction]]
Introduction
------------

Add-on giving support for Spring MVC editors configuration.

[[project-contents]]
Project contents
----------------

This folder contains add-on sources and documents folder `docs` with
documentation of this project.

[[installation-proof]]
Installation Proof
------------------

[[install-the-add-on.]]
Install the Add-on.
~~~~~~~~~~~~~~~~~~~

Install the Add-on in gvNIX/Roo shell with the required commands for
1.1.5-RELEASE version.

[[create-a-web-application]]
Create a web application
~~~~~~~~~~~~~~~~~~~~~~~~

Create a web application with gvNIX/Roo Shell script:: script clinic.roo

Run the add-on command: web mvc binding stringTrimmer
