//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//
//   $ asciidoc -b html5 td-addon-web-binding.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 td-addon-web-binding.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf td-addon-web-binding.adoc


= gvNIX Web Binding add-on
:Project:   gvNIX. Spring Roo based RAD tool
:Copyright: 2010 (C) Dirección General de Tecnologías de la Información - Conselleria d'Hisenda i Administració Pública
:Author:    DISID Corporation, S.L.
:corpsite: www.disid.com
:doctype: article
:keywords: gvNIX, Documentation
:toc:
:toc-placement: left
:toc-title: Table of Contents
:toclevels: 4
:numbered:
:sectnumlevels: 4
:source-highlighter:  pygments
ifdef::backend-pdf[]
:pdf-style: asciidoctor
:pagenums:
:pygments-style:  bw
endif::[]


This work is licensed under the Creative Commons Attribution-Share Alike
3.0 Unported License. To view a copy of this license, visit
http://creativecommons.org/licenses/by-sa/3.0/ or send a letter to
Creative Commons, 171 Second Street, Suite 300, San Francisco,
California, 94105, USA.

[[introduction]]
Introduction
------------

This document contents relative to this add-on.

[[requirements]]
Requirements
------------

This add-on has been reimplemented due to an https://jira.springsource.org/browse/SPR-7077[issue appeared in Spring
3.0.1GA]. Looks like old
way to register property editors globally doesn’t work. Right now the
solution is to use methods annotated with @InitBinder in order to
register custom editors.

In the first release of this revisited add-on, it have to register
StringTrimmerEditor for all the Controllers, or one provided.

When the command `web mvc binding stringTrimmer` is issued, the add-on
will annotate all the classes annotated with @Controller with
@GvNIXStringTrimmerBinder(emptyAsNull=true). This triggers the
generation of an ITD with the method initStringTrimmerBinder annotated
with @InitBinder. This method registers StringTrimmerEditor

[[operations]]
Operations
----------

[source, sh]
----
web mvc binding stringTrimmer [--class path_to_controller] [--emptyAsNull true|false]
----

Performs the needed operations for match the requirements described
above.

[[proof-of-concept]]
Proof of concept
----------------

* http://scmcit.gva.es/svn/gvnix-proof/trunk/petclinic-binding

[[todo]]
TODO
----

In future versions of this add-on it would support, at least, Spring
Editors listed in
http://static.springsource.org/spring/docs/3.0.x/spring-framework-reference/html/validation.html#beans-beans-conversion
Table 5.2
