//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//
//   $ asciidoc -b html5 td-addon-web-binding.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 td-addon-web-binding.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf td-addon-web-binding.adoc


= gvNIX Web Binding add-on
:Project:   gvNIX, un Addon de Spring Roo Suite
:Copyright: 2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y Administración Pública - CC BY-NC-SA 3.0
:Author:    Dirección General de Tecnologías de la Información, Asociación gvSIG, DISID Corporation, S.L.
:corpsite: www.gvnix.org
:doctype: article
:keywords: gvNIX, Documentation
:toc:
:toc-placement: left
:toc-title: Table of Contents
:toclevels: 4
:numbered:
:sectnumlevels: 4
:source-highlighter:  coderay
ifdef::backend-pdf[]
:pdf-style: asciidoctor
:pagenums:
endif::[]


_2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y
Administración Pública - Generalitat Valenciana._
This work is licensed under the http://creativecommons.org/licenses/by-sa/3.0/[Creative Commons Attribution-Share Alike
3.0 Unported License]. If you remix, transform, or build upon the material, you  must give appropriate credit and
distribute your contributions under the same license as the original.

[[introduction]]
Introduction
------------

This document contents relative to this add-on.

[[requirements]]
Requirements
------------

This add-on has been reimplemented due to an https://jira.springsource.org/browse/SPR-7077[issue appeared in Spring
3.0.1GA]. Looks like old
way to register property editors globally doesn’t work. Right now the
solution is to use methods annotated with @InitBinder in order to
register custom editors.

In the first release of this revisited add-on, it have to register
StringTrimmerEditor for all the Controllers, or one provided.

When the command `web mvc binding stringTrimmer` is issued, the add-on
will annotate all the classes annotated with @Controller with
@GvNIXStringTrimmerBinder(emptyAsNull=true). This triggers the
generation of an ITD with the method initStringTrimmerBinder annotated
with @InitBinder. This method registers StringTrimmerEditor

[[operations]]
Operations
----------

[source, sh]
----
web mvc binding stringTrimmer [--class path_to_controller] [--emptyAsNull true|false]
----

Performs the needed operations for match the requirements described
above.

[[proof-of-concept]]
Proof of concept
----------------

* http://scmcit.gva.es/svn/gvnix-proof/trunk/petclinic-binding

[[todo]]
TODO
----

In future versions of this add-on it would support, at least, Spring
Editors listed in
http://static.springsource.org/spring/docs/3.0.x/spring-framework-reference/html/validation.html#beans-beans-conversion
Table 5.2
