//
// Prerequisites:
//
//   ruby 1.9.3+
//   asciidoctor     (use gem to install)
//   asciidoctor-pdf (use gem to install)
//
// Build the document:
// ===================
//
// HTML5:
//
//   $ asciidoc -b html5 ug-addon-web-binding.adoc
//
// HTML5 Asciidoctor:
//   # Embed images in XHTML
//   asciidoctor -b html5 ug-addon-web-binding.adoc
//
// PDF Asciidoctor:
//   $ asciidoctor-pdf ug-addon-web-binding.adoc


= gvNIX Web Binding add-on
:Project:   gvNIX, un Addon de Spring Roo Suite
:Copyright: 2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y Administración Pública - CC BY-NC-SA 3.0
:Author:    Dirección General de Tecnologías de la Información, Asociación gvSIG, DISID Corporation, S.L.
:corpsite: www.gvnix.org
:doctype: article
:keywords: gvNIX, Documentation
:toc:
:toc-placement: left
:toc-title: Table of Contents
:toclevels: 4
:numbered:
:sectnumlevels: 4
:source-highlighter:  coderay
ifdef::backend-pdf[]
:pdf-style: asciidoctor
:pagenums:
endif::[]


_2010 (C) Dirección General de Tecnologías de la Información - Conselleria de Hacienda y
Administración Pública - Generalitat Valenciana._
This work is licensed under the http://creativecommons.org/licenses/by-sa/3.0/[Creative Commons Attribution-Share Alike
3.0 Unported License]. If you remix, transform, or build upon the material, you  must give appropriate credit and
distribute your contributions under the same license as the original.

[[introduction]]
Introduction
------------

Setup Spring MVC default editors to Roo-based project.

[[requirements]]
Requirements
~~~~~~~~~~~~

* JDK 1.6+
* Maven 2+
* gvNIX - Spring Roo - Addon - Web Binding
* Eclipse Helios 3.6.0 (optional)

[[install-addon-services-management]]
Install Addon Services Management
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Options:

* To install gvNIX 0.8.0 that contains the add-on installed.
* OR, to install in Spring Roo 1.1.5
** Trust on PGP KEY ID used to sign the add-on. Note that gvNIX project
members have their PGP KEYs IDs published at
https://code.google.com/p/gvnix/people/list:
+
----------------------------
pgp trust --keyId 0xC5FC814B
----------------------------
** Run the command below:
+
[source, sh]
-------------------------------------------------------------------------
addon install bundle --bundleSymbolicName org.gvnix.web.binding.roo.addon
-------------------------------------------------------------------------

[[use-case-propertyeditors-binding-in-pet-clinic]]
Use case: PropertyEditors Binding in Pet clinic
-----------------------------------------------

Create a new directory for the project:

[source, sh]
--------------
Bash shell:

  mkdir clinic
  cd clinic
--------------

Start gvNIX:

[source, sh]
------------------------------------------------------------------------------
clinic$ gvnix.sh
    ____  ____  ____
   / __ \/ __ \/ __ \
  / /_/ / / / / / / /
 / _, _/ /_/ / /_/ /   1.1.5.RELEASE [rev xxxxxx]
/_/ |_|\____/\____/   gvNIX distribution 0.8.0


Welcome to Spring Roo. For assistance press TAB or type "hint" then hit ENTER.
roo-gvNIX>
------------------------------------------------------------------------------

Create the project:

[source, sh]
----------------------------
roo-gvNIX> script clinic.roo
----------------------------

Add a new report:

[source, sh]
------------------------------------
roo-gvNIX> web binding stringTrimmer
------------------------------------

[[about-the-command]]
About the command
~~~~~~~~~~~~~~~~~

The command performs the following operations:

* Annotates all the classes annotated with @Controller with
@GvNIXStringTrimmerBinder(emptyAsNull=true).
* Generation of an ITD with the method initStringTrimmerBinder annotated
with @InitBinder. This method registers StringTrimmerEditor.

The command accepts the parameters below:

* _class_: Is the class of the Controller we want to register the
StringTrimmerEditor.
* _emptyAsNull_: Based on this option the StringTrimmerEditor will
convert empty Strings to null (emptyAsNull=true) or not.