
  CREATE TABLE "SOSTRATD"."FUNCIO_ROL" 
   (	"IDROL" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"IDFUNCIO" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"DRET" VARCHAR2(1 BYTE) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "FUNCIO_ROL_PK" PRIMARY KEY ("IDROL", "IDFUNCIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SOSTRAT"  ENABLE, 
	 FOREIGN KEY ("IDROL")
	  REFERENCES "SOSTRATD"."ROL" ("IDROL") ENABLE, 
	 CONSTRAINT "FUNCIO_ROL_FK2" FOREIGN KEY ("IDFUNCIO")
	  REFERENCES "SOSTRATD"."FUNCIO" ("IDFUNCIO") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SOSTRAT" ;
 
