
  CREATE TABLE "SOSTRATD"."GLOBAL_CONFIG" 
   (	"IDAPLICACIO" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"IDINFORME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ORDRE" VARCHAR2(500 BYTE), 
	"CAMPS" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"GRUP" VARCHAR2(500 BYTE), 
	"WHEREFILTREFIXE" VARCHAR2(4000 BYTE), 
	"INFFILTREFIXE" VARCHAR2(4000 BYTE), 
	"IDIOMA" VARCHAR2(1 BYTE), 
	"TABLA" VARCHAR2(100 BYTE), 
	"PERMISO" VARCHAR2(12 BYTE), 
	"POPUP" VARCHAR2(1 BYTE), 
	"OCULTS" VARCHAR2(500 BYTE), 
	 CONSTRAINT "GLOBAL_CONFIG_PK" PRIMARY KEY ("IDAPLICACIO", "IDINFORME", "POPUP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SOSTRAT"  ENABLE, 
	 CONSTRAINT "FK_PERMISO" FOREIGN KEY ("PERMISO")
	  REFERENCES "SOSTRATD"."FUNCIO" ("IDFUNCIO") ENABLE, 
	 CONSTRAINT "GLOBAL_CONFIG_R02" FOREIGN KEY ("IDAPLICACIO")
	  REFERENCES "SOSTRATD"."APLICACIO" ("IDAPLICACIO") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SOSTRAT" ;
 

   COMMENT ON COLUMN "SOSTRATD"."GLOBAL_CONFIG"."IDINFORME" IS 'EL NOMBRE DEL ACTION (ej ''tarifa'')';
 
   COMMENT ON COLUMN "SOSTRATD"."GLOBAL_CONFIG"."WHEREFILTREFIXE" IS 'FILTRO FIJO QUE NO TIENE PARAMETROS';
 
   COMMENT ON COLUMN "SOSTRATD"."GLOBAL_CONFIG"."INFFILTREFIXE" IS 'TEXTO INFORMATIVO DEL FILTRO';
 
   COMMENT ON COLUMN "SOSTRATD"."GLOBAL_CONFIG"."IDIOMA" IS 'SI ''S'' SE FILTRARÁ POR IDIOMA';
 
   COMMENT ON COLUMN "SOSTRATD"."GLOBAL_CONFIG"."POPUP" IS '''S'' o ''N''';
 
   COMMENT ON COLUMN "SOSTRATD"."GLOBAL_CONFIG"."OCULTS" IS 'COLUMNAS A OCULTAR';
 
