
  CREATE TABLE "SOSTRATD"."GLOBAL_FILTRE" 
   (	"IDFILTRE" NUMBER NOT NULL ENABLE, 
	"IDAPLICACIO" VARCHAR2(4 BYTE), 
	"IDINFORME" VARCHAR2(100 BYTE), 
	"LABELFILTRE" VARCHAR2(500 BYTE), 
	"WHEREFILTRE" VARCHAR2(500 BYTE), 
	"INFFILTRE" VARCHAR2(500 BYTE), 
	"PORDEFECTO" VARCHAR2(1 BYTE), 
	 CONSTRAINT "GLOBAL_FILTRE_PK" PRIMARY KEY ("IDFILTRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SOSTRAT"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SOSTRAT" ;
 

   COMMENT ON COLUMN "SOSTRATD"."GLOBAL_FILTRE"."LABELFILTRE" IS 'LITERAL QUE APARECE EN EL COMBO, SE COGE DEL PROPERTIES DE LITERALES';
 
   COMMENT ON COLUMN "SOSTRATD"."GLOBAL_FILTRE"."INFFILTRE" IS 'TEXTO INFORMATIVO DEL FILTRO';
 
   COMMENT ON COLUMN "SOSTRATD"."GLOBAL_FILTRE"."PORDEFECTO" IS '''S'' SI HAY QUE APLICARLO POR DEFECTO';
 
