
  CREATE TABLE "SOSTRATD"."OPERADOR_ROL" 
   (	"IDOPERADOR" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"IDROL" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "OPERADOR_ROL_PK" PRIMARY KEY ("IDOPERADOR", "IDROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SOSTRAT"  ENABLE, 
	 CONSTRAINT "OPERADOR_ROL_FK1" FOREIGN KEY ("IDOPERADOR")
	  REFERENCES "SOSTRATD"."OPERADOR" ("IDOPERADOR") ENABLE, 
	 CONSTRAINT "OPERADOR_ROL_FK2" FOREIGN KEY ("IDROL")
	  REFERENCES "SOSTRATD"."ROL" ("IDROL") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SOSTRAT" ;
 
