
  CREATE TABLE "SOSTRATD"."OPERADOR_FILTRE" 
   (	"IDFILTRE" NUMBER(38,0) NOT NULL ENABLE, 
	"IDOPERADOR" VARCHAR2(12 BYTE), 
	"IDAPLICACIO" VARCHAR2(4 BYTE), 
	"IDINFORME" VARCHAR2(100 BYTE), 
	"IDOPEFILTRE" VARCHAR2(500 BYTE), 
	"WHEFILTRE" VARCHAR2(800 BYTE), 
	"WHEESP" VARCHAR2(800 BYTE), 
	 CONSTRAINT "OPERADOR_FILTRE_PK" PRIMARY KEY ("IDFILTRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SOSTRAT"  ENABLE, 
	 CONSTRAINT "OPERADOR_FILTRE_FK1" FOREIGN KEY ("IDOPERADOR")
	  REFERENCES "SOSTRATD"."OPERADOR" ("IDOPERADOR") ENABLE, 
	 CONSTRAINT "OPERADOR_FILTRE_FK2" FOREIGN KEY ("IDAPLICACIO")
	  REFERENCES "SOSTRATD"."APLICACIO" ("IDAPLICACIO") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SOSTRAT" ;
 
