
  CREATE TABLE "SOSTRATD"."OPERADOR" 
   (	"IDOPERADOR" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"NOMOPERADOR" VARCHAR2(30 BYTE), 
	"COGNOM1" VARCHAR2(30 BYTE), 
	"COGNOM2" VARCHAR2(30 BYTE), 
	"TIPOPERADOR" VARCHAR2(1 BYTE) DEFAULT 'I' NOT NULL ENABLE, 
	"IDUSUARI" VARCHAR2(6 BYTE), 
	"BLOQUEJAT" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"MOTBLOQUEIG" VARCHAR2(100 BYTE), 
	"DNI" VARCHAR2(12 BYTE), 
	"DEPARTAMENT" VARCHAR2(75 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TELEFON" VARCHAR2(15 BYTE), 
	"IDIOMADEF" VARCHAR2(2 BYTE) DEFAULT 'CT', 
	"ESTAT" VARCHAR2(1 BYTE) DEFAULT 'A' NOT NULL ENABLE, 
	"DATBAIXA" DATE, 
	 CONSTRAINT "OPERADOR_PK" PRIMARY KEY ("IDOPERADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SOSTRAT"  ENABLE, 
	 CONSTRAINT "USUARI_FK1" FOREIGN KEY ("IDUSUARI")
	  REFERENCES "SOSTRATD"."USUARI" ("IDUSUARI") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SOSTRAT" ;
 
