
  CREATE TABLE "SOSTRATD"."OPERADOR_CONFIG" 
   (	"IDOPERADOR" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"IDAPLICACIO" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"IDINFORME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"ORDRE" VARCHAR2(500 BYTE), 
	"CAMPS" VARCHAR2(500 BYTE), 
	"GRUP" VARCHAR2(500 BYTE), 
	"WHEREFILTRE" VARCHAR2(500 BYTE), 
	"WHEREESP" VARCHAR2(500 BYTE), 
	 CONSTRAINT "OPERADOR_CONFIG_PK" PRIMARY KEY ("IDOPERADOR", "IDAPLICACIO", "IDINFORME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SOSTRAT"  ENABLE, 
	 CONSTRAINT "OPERADOR_CONFIG_FK1" FOREIGN KEY ("IDOPERADOR")
	  REFERENCES "SOSTRATD"."OPERADOR" ("IDOPERADOR") ENABLE, 
	 CONSTRAINT "OPERADOR_CONFIG_FK2" FOREIGN KEY ("IDAPLICACIO")
	  REFERENCES "SOSTRATD"."APLICACIO" ("IDAPLICACIO") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SOSTRAT" ;
 
