Calidad del código
------------------

//Push down title level
:leveloffset: 2

Recomendaciones a seguir en el código
-------------------------------------

En esta sección se incluyen una serie de recomendaciones para mantener
la calidad del código del framework. Estas recomendaciones están basadas
en reglas de buenas prácticas medidas por ciertas herramientas pensadas
para este fin.

* _No dejar bloque de código vacíos_
+
Ya sean excepciones ignoradas o condiciones no utilizadas, es
recomendable no dejar estos bloques sin realizar ninguna operación (los
comentarios no cuentan como operación). Ejemplos:

** En el caso de ignorar una excepción podemos lanzar una traza de
depuración:
+
------------------------------------------
 } catch (Exception toIgnore) {
    LOGGER.finest("Problem do something");
  }

------------------------------------------
** Para condiciones de if que no se utilizan es recomendable eliminarlas
* _Lanzar las excepciones_
+
Suele pasar a veces que en bloques `catch` ser crean las excepciones
_pero se lanzan_ con la sentencia `throw`
* _Implementar el método_ `hashCode` _a la vez que el_ `equals`
+
Para el correcto funcionamiento del método `equals` en una clase con
dicho método personalizado, en fundamental personalizar también el
método `hashCode` utilizando los mismos campos en ambos.
+
Eclipse, en la opción `source` ofrece una herramienta que permite
generar ambos métodos de manera automática a partir de los campos de la
clase que estimemos oportunos.
* _Añadir JavaDoc en todos los métodos públicos._
* _Añadir comentarios en los métodos para explicar bloques de código_
* _Uso de_ `try/finally` _para el cierre de recursos_
+
Siempre que se utilicen recursos, como _Streams_, _objetos de BBDD
(Conexiones, cursores, Statement)_ utilizaremos un bloque `try/finally`
para asegurarnos que los recursos son liberados. Ejemplo:
+
-----------------------------------------------------------------
            InputStream ins = null;
            OutputStream outs = null;
            try {
                if (fileManager.exists(path)){
                    mutableFile = fileManager.updateFile(path);
                } else {
                    mutableFile = fileManager.createFile(path);
                }

                ins = FileUtils.getInputStream(getClass(), file);
                outs = mutableFile.getOutputStream();
                TokenReplacementFileCopyUtils.replaceAndCopy(
                        ins, outs, properties);

                insertI18nMessages();
            } catch (IOException ioe) {
                throw new IllegalStateException(ioe);
            } finally {
                IOUtils.closeQuietly(ins);
                IOUtils.closeQuietly(outs);
            }
-----------------------------------------------------------------
+
Para cerrar los objetos de tipo`*Stream` es recomendable usar el método
`IOUtils.closeQuietly`
* _Evitar el uso de operador_ `+`
+
Es recomendable usar otras opciones como:

** `String.concat`
** `StringBuilder`. Preferentemente antes que `StringBuffer`, a no ser
que se requiera que las instancia se _Thread-safe_
** `String.format`. Para cadenas complejas o con varios argumentos. Ejemplo:
+
-----------------------------------------------------------------------------------------------
 String.format("Esta concatenación de '%s' es mas compleja ya que %s.%s usar varias cadenas.",
                var1, var2, var3)
-----------------------------------------------------------------------------------------------
* _Evitar identificadores de variables o campos de menos de 3
caracteres._
* _Nombres de constantes en mayúsculas._
+
Incluye el `LOGGER`.
* _No modificar un campo estático desde un método no-estático_
* _Añadir el modificador `final` en las propiedades que se establecen en
el constructor y no se van a ser modificadas
* _Eliminar código muerto._
+
El código muerto son métodos privados que nunca se invocan, campos de
clase no usados, variables asignadas que nunca se utilizan en el método,
etc...
* _Iterar sobre_ `Map.entrySet` _en vez de_ `Map.keySet`
+
El coste de iteración es el mismo y se obtiene la clave y el valor a la
vez.
* Precauciones a tener en cuenta en el código fuente del framework para
mejorar la puntuación de SONAR:
** Ver si es posible evitar el uso de Set de URL en addon de temas
(puede ser un grave problema de rendimiento)
** Evitar catch vacios: Ver la posibilidad de log o usar apache commons
para cerrar conexiones.
** Arreglar algunos new XXXException(... sin el throw
** Algunas comprobaciones de is null.
** Limpiar algunas variable no usadas.
* Precauciones a tener en cuenta en el código fuente de los proyectos
generados para mejorar la puntuación de SONAR:
** Algunos if que no usan llaves
** Añadir la generación de los test para las entidades
** Parece que en algún sitio del los aj (creo que en el equals) hay
alguna comprobación de null que se podría mejorar.

//Return level title
:leveloffset: 0
