Distribución de Add-ons
-----------------------

//Push down title level
:leveloffset: 2

Los add-ons de gvNIX actualmente son distribuidos en formato binario a
través de la web de gvPONTIS
(http://www.gvpontis.gva.es/val/gvnix/gvnix-descargas/) tanto por
separado como empaquetados todos juntos en una distribución. También se
encuentra en la web de gvPONTIS el código fuente de los add-ons, la
documentación de cada add-on y la documentación de referencia para el
uso de gvNIX.

Así mismo, también son distribuidos los binarios y los fuentes de los
add-ons de gvNIX a través de un repositorio maven situado en un proyecto
de google code (http://code.google.com/p/gvnix/).

La distribución en el repositorio de google code es necesaria por dos
motivos:

1.  Para permitir la descarga automática de los add-ons a través del
sistema RooBoot de Roo.
2.  Para que los proyecto puedan acceder a sus anotaciones cuando
compilan un proyecto que utiliza un add-on.

Añadir en el proyecto la dependencia al add-on
----------------------------------------------

* Para que un proyecto en el que se está utilizando un add-on pueda
acceder a las anotaciones del add-on deben añadirse dos elementos en el
pom del proyecto gestionado con gvNIX:
+
El repositorio de gvNIX en googlecode:
+
--------------------------------------------------
<repository>
  <id>gvNIX Add-on repository</id>
  <name>gvNIX Add-on repository</name>
  <url>https://gvnix.googlecode.com/svn/repo</url>
</repository>

--------------------------------------------------
+
La dependencia al propio add-on para que el proyecto que se está
gestionando con gvNIX pueda acceder a las anotaciones del add-on:
+
---------------------------------------------------
<dependency>
  <groupId>org.gvnix</groupId>
  <artifactId>org.gvnix.name.roo.addon</artifactId>
  <version>${gvnix.version}</version>
  <type>jar</type>
  <scope>provided</scope>
</dependency>
---------------------------------------------------
* Para definir estos dos elementos se utiliza el fichero
src/main/resources/org/gvnix/name/roo/addon/configuration.xml:
+
-----------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<configuration>
 <gvnix>
  <dependencies>
      <dependency>
          <groupId>org.gvnix</groupId>
          <artifactId>org.gvnix.name.roo.addon</artifactId>
          <version>${gvnix.version}</version>
          <type>jar</type>
          <scope>provided</scope>
      </dependency>
  </dependencies>
  <repositories>
      <repository>
          <id>gvNIX Add-on repository</id>
          <name>gvNIX Add-on repository</name>
          <url>https://gvnix.googlecode.com/svn/repo</url>
      </repository>
  </repositories>
 </gvnix>
</configuration>
-----------------------------------------------------------
+
Reemplazar la cadena "name" con el valor adecuado, para que se
corresponda con el artifactId del add-on.
* Y la inclusión de la información de este fichero en el pom del
proyecto gestionado con gvNIX se realiza a través del siguiente código:
+
---------------------------------------------------------------------
// Install the add-on Google code repository and dependency needed to
// get the annotations

Element conf = XmlUtils.getConfiguration(this.getClass(),
 "configuration.xml");

List<Element> repos = XmlUtils.findElements(
 "/configuration/gvnix/repositories/repository", conf);
for (Element repo : repos) {

    projectOperations.addRepository(new Repository(repo));
}

List<Element> depens = XmlUtils.findElements(
 "/configuration/gvnix/dependencies/dependency", conf);
for (Element depen : depens) {

    projectOperations.addDependency(new Dependency(depen));
}
---------------------------------------------------------------------
+
Este código suele incluirse en el comando setup del addon o en la
primera acción que realice cualquier comando del addon.

Configurar repositorio de google code
-------------------------------------

Ahora el proyecto gestionado con gvNIX intentará obtener la dependencia
del add-on desde el repositorio local de maven y en caso de no
encontrarlo lo irá a buscar al repositorio de gvNIX en googlecode. Es
por ello que es necesario añadir esta dependencia a dicho repositorio
configurando las siguientes secciones en el pom del add-on:

* Antes de la sección "dependencies", añadir las propiedades que definen
el nombre del proyecto en googlecode y el directorio en el que será
almacenada la dependencia:
+
-------------------------------------------------------------------
<!-- DISID: Add google code project name and repo folder values -->
<properties>
 ...
 <google.code.project.name>gvnix</google.code.project.name>
 <repo.folder>org/gvnix/name/roo/addon</repo.folder>
 ...
</properties>
-------------------------------------------------------------------
+
Reemplazar la cadena "name" con el valor adecuado, para que se
corresponda con el artifactId del add-on, separado por '/' en lugar de
'.'.
* Antes de la sección "build", añadir la url del proyecto en googlecode:
+
----------------------------------------------------------------------------
<!-- DISID: Add google code distribution management -->
<distributionManagement>
 ...
 <repository>
  <id>Google Code</id>
  <url>dav:https://${google.code.project.name}.googlecode.com/svn/repo</url>
 </repository>
 ...
</distributionManagement>
----------------------------------------------------------------------------
* Al principio de la sección "build", añadir la extesión necesaria para
utilizar el protocolo que se utiliza para subir la dependencia a
googlecode:
+
----------------------------------------------------
<!-- DISID: Add webdav extension to google code  -->
<extensions>
 ...
 <extension>
  <groupId>org.apache.maven.wagon</groupId>
  <artifactId>wagon-webdav-jackrabbit</artifactId>
  <version>1.0-beta-6</version>
 </extension>
 ...
</extensions>
----------------------------------------------------
* Al final de la sección "build", activar el filtrado del fichero
configuration.xml para que se reemplace la variable $\{gvnix.version}
por el valor de la versión del add-on:
+
----------------------------------------------------
<resources>
 <resource>
  <directory>src/main/resources</directory>
  <filtering>false</filtering>
  <excludes>
   <exclude>**/roo/addon/configuration.xml</exclude>
  </excludes>
 </resource>
 <resource>
  <directory>src/main/resources</directory>
  <filtering>true</filtering>
  <includes>
   <include>**/roo/addon/configuration.xml</include>
  </includes>
 </resource>
</resources>
----------------------------------------------------

Subir dependencia a google code
-------------------------------

* En el fichero de configuración de maven ($M2_HOME/conf/settings.xml)
deberemos configurar el usuario y la clave que da acceso al proyecto en
google code:
+
---------------------------------------------
    <server>
      <id>Google Code</id>
      <username>gvnixscm@gmail.com</username>
      <password>************</password>
    </server>
---------------------------------------------
* Ahora ya podemos desplegar el proyecto en google code ejecutando la
siguiente orden maven:
+
----------------
mvn clean deploy
----------------

Actualizar un addon en una instalación de gvNIX
-----------------------------------------------

Puedes actualizar ejecutando el siguiente comando en la consola de
gvNIX:

----------------------------------------------------------------------
addon upgrade bundle --bundleSymbolicName org.gvnix.service.roo.addon
----------------------------------------------------------------------

Con este sistema, podemos distribuir de forma muy ágil pequeñas mejoras
en algún addon sin necesidad de esperar a hacer una distribución
completa del framework.

//Return to title level
:leveloffset: 0
