Repositorio de gvNIX
--------------------

//Push down title level
:leveloffset: 2

El proyecto gvNIX se guarda en un repositorio con la siguiente
estructura:

-------------------
    doc
    |-- ...
    `-- ...
    code
    |-- addon-occ
    |   |-- pom.xml
    |   `-- src
    ...
    |-- tcon
    |   |-- pom.xml
    |   `-- src
    |-- src
    |   |-- site
    |   `-- ...
    |-- annotations
    |-- target
    |-- ...
     `-- pom.xml
    readme.txt
    LICENSE.TXT
-------------------

Los detalles de esta estructura son los siguientes:

doc::
  En este directorio se almacenará todos los documentos de análisis y de
  _gvMetrica_.
code::
  Este directorio contendrá todo el código fuente y los artefactos
  necesario para genera el proyecto.
code/addon-xxx::
  Este es un ejemplo de un directorio de un add-on genérico para la
  comunidad.
code/addon-cit-xxx::
  Este es un ejemplo de un directorio de un add-on especializado para la
  CIT.
code/tcon::
  Este es un ejemplo de un directorio de una librería o componente _no
  add-on_.
code/annotations::
  Meta-proyecto para la generación de librerías con las anotaciones
  necesarias para los add-ons.
code/src::
  Directorio para fuentes de proyecto genéricos, ya sean para generar el
  site o documentación (como la que está leyendo), empaquetado, etc.
code/target::
  Directorio de trabajo de maven, en el repositorio estará vacío.
code/pom.xml::
  Fichero de proyecto maven principal o padre.

//Return to title level
:leveloffset: 0
